### ISSUE TITLE
Token requirement on login page

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#3325]
_Reported by rosali on 12 Mar 2011 07:02 UTC as Trac ticket #1487829_

When logging out and let the login page open until the session expires then error $messages['invalidrequest'] is raised because the CFSR token is not available in the session anymore.

I assume that keep-alive request should be triggered but it look like it does not send requests to keep the session alive (the timestamp in the session table does not change).

_Migrated-From: http://trac.roundcube.net/ticket/1487829_

**Comment by alecpl** [comment]
Even if we add a keep-alive request that will force session to not timeout, this will not fix the case when a user leaves the browser with logon page but e.g. closes the laptop (i.e. closes Internet connection). I don't see a solution for this.

**Comment by thomascube** [comment]
Unless we disable the CSRF check, there's no real solution for this very rare case. Closing as wontfix.

**Comment by raph431** [comment]
While reverse CSRF attacks can be prevented by this hidden _token in the login form, this random token also prevents the login form to be checked against a fingerprint. Yes, there is TLS, which ensures I get the same form, that is served on the server, but it does not protect me from a tampered login form. Now if my browser would let me calculate a fingerprint of the login form, I cannot check against this fingerprint, because the login form changes every time (because of this CSRF _token). The only attack this prevents is a reverse CSRF attack, so someone could log me into roundcube, and I could inadvertently use the attackers email account. Not a big risk IMO and its prevention with a CSRF token prevents me from verifying the integrity of the login form.
