### ISSUE TITLE
Better support for IMAP folders that cannot contain both folders and messages

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5057]
_Reported by jed on 27 Dec 2012 10:27 UTC as Trac ticket #1488882_

IMAP servers usually allow to create a folder structure where folders could contain subfolders and/or messages to organize email storage (not only as part of the INBOX). In Roundcube this seems not to be possible at the moment. Additionally it's not possible to distinguish between normal folders which could contain messages and folders which couldn't contain email. UW-IMAPD e.g. only allows to create folders which contains folders OR folders which contains messages. Afaik other IMAP servers may allow to contain both at the same time.[In Mozilla Thunderbird you could find different options which allow to influence its behavior.[[BR]([BR]]
[[BR]]
e.g.)]
1. In the advanced server settings (settings->server settings->advanced) you'll find the parameter "Server supports folders that contain subfolders and messages" -> 20121227_tb-imap-folder-options.png[If the named parameter (1.) is not checked and you want to create a new folder, you have to decide if the folder you want to create should contain folders OR messages. If the named parameter (1.) is checked the mentioned question is not asked during folder creation -> 20121227_tb-new-folder-creation.png[[BR]([BR]]
2.)]
[[BR]]

_Migrated-From: http://trac.roundcube.net/ticket/1488882_

**Comment by lx-s** [comment]
Do you still need a testing account?

**Comment by alecpl** [comment]
Yes, though I don't know how fast I could start work on this. Send credentials to alec at alec.pl, please.

**Comment by lx-s** [comment]
Credentials are in your inbox :)

**Comment by alecpl** [comment]
Ok, so how would I see this implemented.
1. Add a new configuration option `imap_dual_use_folders` that defaults to `true`. (ideas for better option name?). I think there's no need to make it user configurable via Preferences, but we can add it later.
2. In Folder creation form when `imap_dual_use_folders=false` add "Can contain only" with selector containing two options "mail messages" and "folders". If user selected "folders" option we have to add the hierarchy separator at the end of the folder name. Such folders will then have \NoSelect flag assigned. We should also not subscribe such folders, I suppose.
3. I'm not sure we should display such selector in folder edit form, because such change would require folder delete. Maybe we'd display just read-only information. We should probably also hide Messages/Size entries on \NoSelect folders.
4. Additional work needed in Archive plugin when using Archive folder dividing, on subfolders creation or when changing Archive mode from/to None.

What do you think?

**Comment by lx-s** [comment]
1. `imap_dual_use` sounds fine to me, as there seems to be no specific term for this. Thunderbird also calls this preference `mail.server.server1.dual_use_folders`. Default value `true` is definitely the most reasonable.
2. This sounds like the best option. In case of All-Inkl, their webmail client implements it exactly like this. The same UI design is also used by Thunderbird. As for subscribing: Currently, when Use IMAP Subscriptions is set to `false`, Roundcube displays all folders, even `\NoSelect` as selectable. When trying to move a message to a folder, that can contain only sub-folders, Roundcube displays an error message "Mailbox not selectable". After setting `Use IMAP Subscriptions` to `true` (and subscribing to all selectable folders), roundcube displays these `\NoSelect` folders greyed out. That should be the default then.
3. I wouldn't. Editing such a folder to a different mode would seem like a costly operation and maybe have unexpected results for the user. In both cases a new folder would have to be created (naming?) and alle subfolders/all messages from the current one would have to be moved there. Imho this should better be handled by the user.
4. This sounds exactly like problem the above point: Roundcube would have to create a temporary folder and move all the messages inside, then delete the old archive folder and rename the temporary one and set the special use flag `\Archive` - if the server supports those. Maybe -in a first iteration- disable the archive mode selection and default to none, when `imap_dual_use_folders` is set to `false`?

**Comment by alecpl** [comment]
5. Make sure that folder rename (or move) will not change the folder type.

**Comment by alecpl** [comment]
Implemented with one addition: automatic detection of the server capability to use "dual use" folders.
