### ISSUE TITLE
3 Column Layout for Larry Skin

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5093]
_Reported by hamayun on 19 Dec 2013 01:56 UTC as Trac ticket #1489484_

It would be really very productive if message preview is displayed on right instead of below the message list. That is much more efficient use of screen real estate than current default.

_Keywords: 3 cloumn layout like MS Outlook_
_Migrated-From: http://trac.roundcube.net/ticket/1489484_

**Comment by alecpl** [comment]
Work in progress, https://kolabian.wordpress.com/2016/09/17/widescreen-layout-aka-three-column-view/

**Comment by alecpl** [comment]
Merged into master.

**Comment by fiftyz** [comment]
The columns should be also configurable including in Widescreen mode... If not, this feature is quite unusable if you have a custom layout. :-(

**Comment by MarcinOrlowski** [comment]
@alecpl which release features side preview pane?

**Comment by alecpl** [comment]
3-column layout was implemented in 1.3-beta. There's a milestone assigned to this ticket.

**Comment by taxilian** [comment]
I'm glad someone likes the 3 column layout; I absolutely can't stand it. Is there a way to put it back still? I'm new to the project, so I apologize if I just haven't found something obvious.

It is honestly baffling to me how anyone can find the 3 column layout to be an efficient use of space, since to me it's exactly the opposite, but to each their own I suppose!

**Comment by taxilian** [comment]
Ahh, I found it -- very sorry! I just needed to expose my ignorance publicly and there it was!
