### ISSUE TITLE
separate mobile interface is needed

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5102]
_Reported by piratepraveen on 28 Apr 2014 08:48 UTC as Trac ticket #1489838_

On android phones, K9 mail can do email pretty well, but Firefox os is pathetic. Their default email app does not work and they don't care about it. I have no hope it will ever work. So I'm forced to use their mobile browser to check emails. I won't be alone in this boat I'm sure, all people checking mails via mobile browsers are affected.

It needs really a lot of patience to get it to work on the mobile browser. You need to zoom in to see the list of mails and then try a few times to open the threads, then try ten times to open the individual message, in between it will zoom in and out when you click, and finally when it
opens your browser crashes. You have to start over and you need to be a believer and pray for
this to actually work.

So we should have a mobile interface,

which has only minimal screen size requirements. All menus should be foldable and should be placed at the bottom or as a drop down list. gmail mobile interface would be a good place to look for possibilities.

If someone can provide a time estimate, I'm willing to run a crowd funding campaign to get this feature developed (along with #1369135). 

_Keywords: mobile_
_Migrated-From: http://trac.roundcube.net/ticket/1489838_

**Comment by julmot** [comment]
:+1: It should be an AngularJS + Bootstrap + SCSS framework. 
As this issue is still open, is there any help necessary?

**Comment by julmot** [comment]
:+1: 

As this issue is still open, is there any help necessary?

A mobile optimized roundcube should:
- be based on AngularJS 2 (will probably be stable when this will be released)
- be based on SCSS
- contain JSDOC comments
- contain karma + jasmine + Sauce Labs (cross browser) tests
- contain ESLint
- should additionally be designed in a prototype first, to make sure it fits usability requirements and has a good user experience

**Prerequisite**
- RESTful API available to make AJAX requests

To answer the first question about time estimate, from my point of view this would take at least 3 months for a high quality realization.

**Comment by alecpl** [comment]
We do not plan working on this on current code base. We have Roundcube Next for this.

**Comment by qua-bla** [comment]
Is there hope that you would pull a bunch of small css adjustment to the Larry skin to make RC work on small screens? If this is the case, I would give that a try.

**Comment by julmot** [comment]
@qua-bla to whom is your question?

**Comment by qua-bla** [comment]
@julmot to folks that can pull i.e. RC project members

**Comment by lahcejopa** [comment]
Are there any plans to make that happen either in the form of the skin or a standalone mobile app or this feature request just died/got abandoned with a WONTFIX tag?

**Comment by qua-bla** [comment]
I hoped for a sign from the RC team. Looking at #5093 there is stuff 
happening to the skins.


I will spend a day this week to see if it is realistic to get all the 
"position absolute" mess (these skins were created before css flexboxes 
were available) usable for mobile via media queries. I will report if I 
gave up.

A bit annoying that I have to setup a working dev-layouts version of 
RC. I will start working on 1.2 first since the basic problems should 
be identical.

**Comment by qua-bla** [comment]
Okay, this is impossible since there is JS stuff going on setting html `style` attributes. Creating another skin is also not an easy solution since skins currently can be delivered depending on the device form. I'm out.

**Comment by basdds** [comment]
Any updates on roundcube for mobile browsers in release 1.3? I've used some mobile skins working flawlessly with roundcube by now... 

But native support for mobile browsers would be a milestone for the project imho!

**Comment by th3penguinwhisperer** [comment]
Yet another user who would like to see a responsive RoundCube. On my smartphone I can't even see the subjects. I don't get this feature is already postponed for 2 years. Is RC still being worked on or abandoned as well by the devs?

**Comment by smares** [comment]
Well, there was the idea about Roundcube Next as a total redesign incl. mobile view and money was even collected through crowdfunding, but apparently it was a scam. Never received any update on that and never got my money back either.

**Comment by alecpl** [comment]
Work is in progress (https://github.com/roundcube/elastic) Hopefully will be part of 1.4.

**Comment by th3penguinwhisperer** [comment]
@alecpl Cool! Really looking forward to finally have this as part of Roundcube!

**Comment by xshadow** [comment]
@alecpl Would love to see that too

**Comment by HighlyFavoredBA** [comment]
@alecpl:  Is Elastic still expected to be ready in 1.4?!  Is 1.4 going to have a 177 by 49 area for logo banners?!  I don't see a banner image in the current Elastic dev files.  Should 1.4 be ready by spring 18?  :--)

**Comment by HighlyFavoredBA** [comment]
@alecpl: Is Elastic still expected to be ready in 1.4?! Is 1.4 going to have a 177 by 49 area for logo banners?! I don't see a banner image in the current Elastic dev files. Should 1.4 be ready by spring 18? :--)

**Comment by alecpl** [comment]
The Elastic skin has been merged into the Roundcube repo.

There's no banner in Elastic. All you can do is to replace the "watermark" image. I think 1.4-beta will be released somewhere in 2018-Q2.
