### ISSUE TITLE
Non-indent Top Posting

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5105]
_Reported by henrie1 on 15 May 2014 13:16 UTC as Trac ticket #1489895_

Please add a new feature to NOT indent reply emails by including the ">" sign as the first character of each line in the quoted/original email.  Current business email etiquette requires reply-to emails to NOT indent the quoted emails and to include the quoted emails below your new post.  

For motivation, please read http://en.wikipedia.org/wiki/Posting_styles and pay attention to the Top-posting (TOFU) style guide and notice the words "many users seem to accept top-posting as the "standard" reply style."  This option alone will allow users of roundcube to appear more up-to-date in their email etiquette.

_Keywords: quote reply-to tofu top-posting greater-than indent_
_Migrated-From: http://trac.roundcube.net/ticket/1489895_

**Comment by jasonbassford** [comment]
I'm struggling because I, personally, always use inline replies. The whole notion of top-posting, which I am forced to do when at an office that uses Word (which is annoyingly too common, as there are much better alternatives), is actually painful. It quickly ends up being nothing more than a "wall of text" which adds nothing useful whatsoever to any conversation. But it's also too time-consuming to manually copy / paste / edit the junk that top-posting formatting gives you and turn it into something that results in a meaningful dialogue—and one where the recipient actually understands what you're talking about when you refer to something.

The reason I'm struggling with roundcube is because I need to use HTML in order to get a proportional font that properly distinguishes a hyphen from an em-dash. That one detail aside, text-only composition behaves in exactly the way that I'd like. In particular, when it comes to quoting.

I'm using HTML in roundcube at the moment. But, since I use roundcube for my personal email—where, opposed to work email, I care more about properly representing my own personal style—I *am* copying / pasting / editing in order to use inline replies. Sometimes I simply un-blockquote everything and then insert my own > characters, other times I leave the blockquoting. (In both scenarios, however, I still do break text into individual pieces and write my replies underneath those.)

There is no reason at all for personal attacks here on what people believe. Whatever somebody wants to do, is valid for their use of the product. I vote for either an option in the UI itself—or a documented method of changing the TInyMCE code to do the same thing. (Which could be as simple as overriding the CSS used for blockquote and replacing it with prepended > characters on each text line—say first-line::before. Assuming there was an easy method of applying CSS overrides, something I haven't yet discovered.)

**Comment by alecpl** [comment]
I'm more positive on this option these days. Could we agree that this option makes sense only with top-posting, i.e. I'd make the checkbox disabled for when the bottom-posting is selected.

Another question. Do we need to modify the reply header for when this is enabled? I mean
```
my reply

-------- Original Message --------
From: Danny <danny@example.com>
Sent: Tuesday, October 16, 2007 10:01 AM
To: Jim <jim@example.com>
Subject: RE: Job

Whoa!  Hold on.  I have a job scheduled at 5:30 which mails out
a report to key tech staff.  Could you please push it back an hour?
Danny
```
looks more clear than what we have now, i.e.:
```
my reply 

On Tuesday, October 16, 2007 10:01, Danny <danny@example.com> wrote:
Whoa!  Hold on.  I have a job scheduled at 5:30 which mails out
a report to key tech staff.  Could you please push it back an hour?
Danny
```

**Comment by alecpl** [comment]
Implemented.
