### ISSUE TITLE
Allow Setting Default Mail View  (Unread vs. All)

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5140]
_Reported by iredduser on 3 Jun 2015 13:00 UTC as Trac ticket #1490418_

Can Options be added in the RoundCube configuration to customize the Default Mail View. This would mean Sort ascending/descending, show Unread e-mail instead of All e-mail and etc...

Sort by (column) ascending/descending
Mail Filter: Unread, All, Unanswered, etc..

Thank you in advance!

_Migrated-From: http://trac.roundcube.net/ticket/1490418_

**Comment by alecpl** [comment]
You can already set default sorting. I think setting the filter to something different than All by default is a rare case.

**Comment by clackwell** [comment]
> I think setting the filter to something different than All by default is a rare case.

To be precise: It is completely impossible because roundcube does not allow for it.

My work-flow:

- Leave open/viewed emails in unread state until I manually change them to "read" status.

- Change to a folder, switch the filter to show only "unread".

This way I see old and new unread emails at one glance (provided the list is not too long; but even when scrolling is needed I will only scroll through unread emails anyway).

I have created a Greasemonkey script achieve this, but having it built would be very nice.

To me it seems that this ticket got closed based on "I personally do not see the need for this". But in such cases it may be better to ask for some justification or work-flow that helps understand the requirements or need.

**Comment by rmcaninch** [comment]
Perhaps use the Preview pane with the preference set to Never mark as read?

Typical email client will mark the message read when you open it. If I open an email and want to followup later, I might flag it. Or move it to a "working in progress" folder. Or on the rare case, mark it as unread. This gives a more consistent work flow from multiple email clients.

**Comment by clackwell** [comment]
> Perhaps use the Preview pane with the preference set to Never mark as read?

If this was in reply to my last comment:

That is what I am doing/using.

But despite that, these facts remain:

- My list of emails contains older and newer unread emails.
- Only unread emails are relevant to me.
- In order to see all emails "relevant to me" I need to switch to the "Unread" filter manually all the time, instead of it being the default (for me).

Would I be using "flagging", I would have the same problem, and an additional one:

I could not see older (=scrolled out of view or to the next page) and newer flagged and new emails at one glance.

**Comment by alecpl** [comment]
Thunderbird has "Keep filters applied when switching folders" button. We could consider implementing something like that and then extending this feature to remember and use the state on next logon. Feel free to provide pull requests.

**Comment by magdesign** [comment]
Is there any solution so far?

I'd also like to keep my unread mails always on top, as soon as I read them, they get sorted by date as usual, had this feature on cloudmail.

**Comment by tritasapostolos** [comment]
I have the exact same requirement...

**Comment by the0ne** [comment]
+1 as I have the exact same requirement...


> Thunderbird has "Keep filters applied when switching folders" button.

I guess that could work 👍🏻
