### ISSUE TITLE
Drop legacy browser support

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5167]
_Reported by @alecpl on 8 Feb 2016 08:44 UTC as Trac ticket #1490656_

Which means:
1. Remove legacy_browser plugin
2. Use jQuery 2.x or 3.x (when ready)
3. Remove code like this https://github.com/roundcube/roundcubemail/blob/master/program/steps/mail/get.inc#L310
4. Remove js code for where bw.ie7 and bw.ie8 (and likely bw.ie9) is used.
5. Use jQueryUI 1.11 or even 1.12 (when ready).

_Migrated-From: http://trac.roundcube.net/ticket/1490656_

**Comment by skaero** [comment]
Multiple projects that I'm working on have just dropped support for IE < 11 since Microsoft doesn't even support it anymore. If this is added in 1.3 and 1.2 goes LTS when 1.3 comes out that would give any one who needed it another year or so to get off of the old stuff. I think its a great idea and support it 100%.

**Comment by raoulbhatia** [comment]
I am OK with removing legacy browser support, however, I am using roundcube for personal/family use only and cannot comment on ISP usage.

**Comment by alecpl** [comment]
Done.
