### ISSUE TITLE
Call to undefined method Crypt_GPG_SubKey::usage() ../enigma/lib/enigma_driver_gnupg.php

### ISSUE THREAD

**Issue by cscholz** [roundcube/roundcubemail#5217]
I'm using roundcube 1.2-rc. When I enable enigma and try to add,generade or import a PGP key the following error will be logged:
`PHP Fatal error:  Call to undefined method Crypt_GPG_SubKey::usage() in /var/customers../plugins/enigma/lib/enigma_driver_gnupg.php on line 435`

Roundcube is running:
- Debian 7
- Apache 2.2.22-13+deb7u6
- PHP 5.5.30-1~dotdeb+7.1

BR Chris

**Comment by alecpl** [comment]
Looks like you don't have Crypt_GPG >= 1.4.0, which is a requirement.

**Comment by himbeere** [comment]
I have the exact same error. Crypt_GPG 1.4.0 is installed on my machine.

**Comment by alecpl** [comment]
The missing method was added in 1.4.0, so you don't have 1.4.0 or you have another instance of the package which is used instead.

**Comment by himbeere** [comment]
Hello Alecpi.

Thanks for your answer. I've search for SubKey.php on my machine and found:

`
 ~ #  find / -name SubKey.php
/usr/share/php/Crypt/GPG/SubKey.php
/var/www/webmail/htdocs/plugins/enigma/lib/Crypt/GPG/SubKey.php
/var/www/webmail/htdocs/program/lib/Crypt/GPG/SubKey.php
/var/www/webmail/htdocs/vendor/pear-pear.php.net/Crypt_GPG/Crypt/GPG/SubKey.php
meine-oma ~ # equery b SubKey.php
 * Searching for SubKey.php ... 
dev-php/PEAR-Crypt_GPG-1.4.1 (/usr/share/php/Crypt/GPG/SubKey.php)
meine-oma ~ #
`

Maybe the problem is there are more than one of them?

**Comment by himbeere** [comment]
Hello Alecpi.

I did a clean install of roundcubemail and now creating a key works. Will go on with testing. One short question. I can't find a way to import a key. Is that functionality included already?

thanks and cheers

**Comment by himbeere** [comment]
Never mind. Found the button.

**Comment by cscholz** [comment]
Does someone know how to install  Crypt_GPG >= 1.4.0 on Debian Jessie?

**Comment by rmcaninch** [comment]
Looks like it is in Stretch. Check Debian documents on using that as a repository for apt / aptitude.

**Comment by oxivanisher** [comment]
Yeah ... not really a solution, since it wants to update a lot of other stuff or even breaks the system. Aptitude does not find a usable solution... I guess users of the current stable have to wait until debian includes the 1.4.0> version... This can be checked here: https://packages.debian.org/search?keywords=php-crypt-gpg

**Comment by cscholz** [comment]
Does someone know how I can check if Crypt is correctly installed and usable by php?
Crypt_GPG is installed in my debian machine but enigam fails

$pear install Crypt_GPG
pear/Crypt_GPG is already installed and is the same as the released version 1.4.3

**Comment by regisb** [comment]
Just wanted to mention that I had the same issue in 1.4.1. My roundcube install exists for a long time and has been upgraded since I don't know when. There were old package folder lying around and they included older versions of the Crypt package. I managed to solve this issue by removing them:

    rm -rf ./plugins/enigma/lib/Crypt/
    rm -rf ./plugins/enigma/vendor/

**Comment by ediazrod** [comment]
> Just wanted to mention that I had the same issue in 1.4.1. My roundcube install exists for a long time and has been upgraded since I don't know when. There were old package folders lying around and they included older versions of the Crypt package. I managed to solve this issue by removing them:
> 
> ```
> rm -rf ./plugins/enigma/lib/Crypt/
> rm -rf ./plugins/enigma/vendor/
> ```

Thanks This was the way to solve my issue.

Regards!
