### ISSUE TITLE
Require SMTP server - drop mail() support

### ISSUE THREAD

**Issue by alecpl** [roundcube/roundcubemail#5340]
There are issues with sending mail using PHP's mail() function. In my opinion it is not reliable enough and not good for a sophisticated use we do in Roundcube. So, I'm proposing to require smtp_server (maybe setting it to 'localhost' by default) and remove the code path where we use mail().

**Comment by skaero** [comment]
I know that a lot of people use the PHP mail() setup simply because adding SMTP info is one extra step in the installer or because there is some problem with there SMTP info. Because of that I think a lot of users will have problems updating Roundcube if support was removed.

That said having PHP mail() also causes a lot of problems ("why is my mail getting caught in spam filters?", "why can I no longer send email?", etc.) so I think the long term benefit outweighs the short term pain of helping users through upgrades.

**Comment by alecpl** [comment]
Sample issues: #5322 #5338.

**Comment by iredmail** [comment]
* With smtp server defaults to `localhost` or `127.0.0.1`, it won't be a big problem.
* It's always good idea to encourage good practice, asking users to set a smtp server is not that hard and bad.

**Comment by raoulbhatia** [comment]
I am in favor of dropping PHP mail() support.

**Comment by alecpl** [comment]
Done. If anyone is in need of mail() support would be able to write a plugin using message_before_send hook.

**Comment by kohlrak** [comment]
> * With smtp server defaults to `localhost` or `127.0.0.1`, it won't be a big problem.
> 
>     * It's always good idea to encourage good practice, asking users to set a smtp server is not that hard and bad.

It is, because any decent level of security is near impossible to debug with postfix, which is the most common one used. I just spent several hours looking for a solution and i want to give up on roundcube, because this is unnecessarily complicated now.

> Done. If anyone is in need of mail() support would be able to write a plugin using message_before_send hook.

Seems this was never created.
