### ISSUE TITLE
responses: expose 'format' property in settings ui

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [roundcube/roundcubemail#5458]
currently, internally, `responses` support `format` (html va text) property:
https://github.com/roundcube/roundcubemail/blob/master/program/steps/settings/responses.inc#L37
but it is not exposed to the user in settings ui

while developing 
https://github.com/random-cuber/responses

we were forced to use a `detector` workaround
https://github.com/random-cuber/responses/blob/master/responses.js#L280

which will likely be confusing for users

please expose `format` property in settings ui

see #5456 #5457

**Comment by alecpl** [comment]
We already have a ticket for HTML responses support - #5315. We can't just "expose" the format property. We have to implement HTML editor there. Then, as in other places we should support including images, etc. This would require to not store responses in user preferences, but use a separate database table instead. Also, because of size, using responses in compose should not load all responses content at once, but get the content of each response separately on request. So, pretty big task.

**Comment by Andrei-Pozolotin** [comment]
ok, I see. 

in this case please resolve #5456 #5457 
so the  plugin https://github.com/random-cuber/responses
can fill the need for the time being, and does not have to rely on "code replace hacks"

**Comment by alecpl** [comment]
I'm closing this as a duplicate (or wontfix).
