### ISSUE TITLE
attachment pane permanently showing in message preview since ea816a0

### ISSUE THREAD

**Issue by JohnDoh** [roundcube/roundcubemail#5484]
since ea816a0 the attachment pane (small grey box on the right hand side) is always shown during message preview not matter if there are attachments or not. it looks like messagepreview.html does not include header.html and so the UI is never init'd

**Comment by JohnDoh** [comment]
A quick search suggests that all these templates may have a similar issue. They all include footer.html and so used to call UI.init() but they do not inclide header.html so don't any more.

contactedit.html
contact.html
contactsearch.html
folderedit.html
identityedit.html
login.html
responses.html
settingsedit.html

**Comment by alecpl** [comment]
Ouch. This is in release-1.2 branch too.

**Comment by alecpl** [comment]
Fixed. Hopefully both these changes aren't very backward incompatible (for plugin and skin authors perspective).

**Comment by rinogo** [comment]
Is this Issue for the problem demonstrated in the screenshot below?
![image](https://user-images.githubusercontent.com/3732514/33042740-1fb102f2-ce00-11e7-9daf-bd425be9efb9.png)


I'm on 1.3.3, but the conversation above suggests that this was fixed in 1.2.3. Any thoughts on what might be going on? Or, perhaps this is a new bug?

![image](https://user-images.githubusercontent.com/3732514/33042686-f42fbd94-cdff-11e7-9ff6-ffe3598f52b9.png)

**Comment by alecpl** [comment]
@rinogo, no, this is another issue. You should check browser console for errors. Also disable cpanel* plugiins for test.

**Comment by rinogo** [comment]
@alecpl Thanks for the guidance! There are some console errors, but I wasn't sure if they were relevant. We were using minimally-customized theme which was created on an older version of Roundcube. Even though the custom theme was forked from the default Roundcube theme, apparently there have been some backwards-incompatible changes to RC since we made the theme.

I made a new copy of the "current" default Roundcube theme and performed our minimal customization steps within the new theme. Everything is working fine now!

Thanks!
