### ISSUE TITLE
Purge deleted mails older than X days

### ISSUE THREAD

**Issue by thomascube** [roundcube/roundcubemail#5493]
The mailbox maintenance settings offer to empty the trash on logout. I'd would love to see an option to purge only deleted mails older than 30/60/90 days very much similar to how Gmail handles the trash.

This would be a simplified alternative to full retention policies as requested in #5029.

**Comment by CRtEurope** [comment]
I would second that. This would be a great feature. Thumbs up.

**Comment by rmcaninch** [comment]
That would be a nice option to have.

**Comment by TVBZ** [comment]
You have my vote.
Strange that it's not there yet. :(

**Comment by rpv-tomsk** [comment]
This option can be configured on Dovecot IMAPd server (autoexpunge setting).

**Comment by TVBZ** [comment]
> This option can be configured on Dovecot IMAPd server (autoexpunge setting).

Yeah. But we need an option that can be configured per email address, on user level.
Maybe even folder based, to make it more flexible and solve more different situations.

Not every user has same retention policy. And for internal company emails, there might not be a retention at all. But for some (or many) like myself it is required because of EU privacy law (GDPR).

**Comment by tidechris** [comment]
Merry xmas guys, 

actually I try to implement a filter, that doesn't delete the complete mail but the attachments after "X-Days". 

Here's my actual rule config: 
1. Mails matches more then 1 MB
2. Mails which are older then 90 days

Action:
- ???

The question I have is, if there will be an integration of an actions to delete the attachments separated from the mail body. 

All the best,
Chris

**Comment by alecpl** [comment]
Implemented.
