### ISSUE TITLE
How to use the CRAM - MD5 way in Mysql statement of password code

### ISSUE THREAD

**Issue by lilongen1** [roundcube/roundcubemail#5599]
With the roundcube own password plugin to modify the password, but postfixadmin password encryption is CRAM - MD5,The following sentence is clear,
// Default: "SELECT update_passwd(%c, %u)"
**$config['password_query'] = 'UPDATE mailbox SET password=%d WHERE username=%u';**
In phpmyadmin see CRAM - MD5 encoding is
{CRAM-MD5}e242eae7d898607cdade67c99081da7b56fc60aa9acfceb9016b21c80b6872f3
ABC @ 123456 (corresponding)
How to write the SQL statement to update the password?
thanks!

**Comment by rmcaninch** [comment]
This is not a roundcube issue. Try http://www.roundcubeforum.net for assistance on configuring your email server.

I don't see a Postfixadmin driver for the password plugin. That CRAM-MD5 uses the dovecotpw command to hash the password so you can't do that in a simple SQL statement. You would need to extend the plugin to hash the password in the same way Postfixadmin does. One of the other encryption types in Postfixadmin, for example cleartext or md5 could use the sql driver.

**Comment by lilongen1** [comment]
Thank you for your help,I may not be able to express clearly.
I met problems when using roundcube password plug-in, of course I was using a postfix, so contact with it
I say it in detail
I made A contrast in the database, established A, B two E-mail, then A password into A and B. The observation database that the encryption method using password plug-in and postfix encrypted in a different way.
 of course, it's certainly not the plug-in question, where is my Settings has a problem, but I have a problem
I use in the postfix is CRAM - MD5 encryption, in the plug-in configuration file in this way, I was set up in the right place?
**config.inc.php:**
**$config['password_dovecotpw_method'] = 'CRAM-MD5';**
**$config['password_query'] ='UPDATE mailbox SET password=%c WHERE username=%u';**
<img src="https://raw.githubusercontent.com/lilongen1/ziluopao/master/roundcube%20qu11.png"/>

**Comment by rmcaninch** [comment]
I do not understand what you are doing.

Postfixadmin is hashing the password in a different way than what the password plugin can match. This will not work. Two options.

1. Write PHP code to make the password plugin do what you want.
2. Change the encryption method you are using in Postfixadmin (this has other repercussions). So that the password plugin can match Postfixadmin.

**Comment by alecpl** [comment]
Configuration issue.

**Comment by ayazka** [comment]
@lilongen1 
 I also had problems with password encryption. All you should do is: 
1)setup the plugin path:
// Path for dovecotpw/doveadm-pw (if not in the $PATH).
// Used for password_algorithm = 'dovecot'.
 $config['password_dovecotpw'] = '/usr/bin/doveadm pw'; // for dovecot-2.x
//$config['password_dovecotpw'] = '/usr/local/sbin/dovecotpw'; // for dovecot-1.x

2) setup the encryption mode:
// Dovecot password scheme.
// Used for password_algorithm = 'dovecot'.
$config['password_dovecotpw_method'] = 'CRAM-MD5';

3) database connection
$config['password_db_dsn'] = 'mysql://USER:PASS@127.0.0.1/mail';

4) update query
$config['password_query'] = "UPDATE mailbox SET password=%D, modified=NOW() WHERE username=%u LIMIT 1";

REMEMBER to use %D in query string, instead of %c  as you mentioned before!

**Comment by devuniverse** [comment]
> 
> 
> Configuration issue.

How does highlighting that without a concrete solution help anyone?
