### ISSUE TITLE
replymode: replyempty is not saved

### ISSUE THREAD

**Issue by tomsommer** [roundcube/roundcubemail#5612]
The "Do not quote the original message"-setting is not saved correctly, the setting just resets after reload.

**Comment by alecpl** [comment]
Works for me. What version? Did you click the Save button? Did you try with disabled all plugins?

**Comment by tomsommer** [comment]
Roundcube Webmail 1.2.3
Did click save

Did not try and disable all plugins. Other settings save fine.

**Comment by alecpl** [comment]
What browser? Did you try with different?

**Comment by alecpl** [comment]
No feedback. Unable to reproduce.

**Comment by tomsommer** [comment]
Chrome 57.0.2987.98

http://i.imgur.com/aEYoWND.gif

**Comment by tomsommer** [comment]
Can you please reopen?

**Comment by alecpl** [comment]
I need a way to reproduce the issue. As I said it works for me. Did you try with disabled all plugins? Did you try with different browser?

**Comment by devaabhik** [comment]
I experience  the same issue... 

"The "Do not quote the original message"-setting is not saved correctly, the setting just resets to : "Start new message above the quote" After saving "Compossing messages" options page.

I am using Chrome ver: 60.0.3112.113,  tried with all but "google docs extensions" pluggins disabled, same results...

Customer wants to reply with a "brand conscious"  formated HTML message, to information request messages (Text e-mails) sent by a contact form on their website. 

Including the "original, DB oriented email"  from their website, heavily detracts from the image of customer care appreciation of the company, specially because they deal with treating kids with ADD or dislexia, and parents need reassuarance of gentle human tratment, not a line on a DB...

Any how, this is a bug which at least on my browser does not work.

Hopefully you can get it sorted
