### ISSUE TITLE
Roundcube sign in link

### ISSUE THREAD

**Issue by Chaimadai** [roundcube/roundcubemail#5669]
Hello

I would like to know if anyone can help me please to find out for the link for signing in into Roundcube mail.

I got my email adresses and password but I can t find the link to sign in.

Can anyone knows about it.

Thanks in advance,

Chai

**Comment by alecpl** [comment]
Roundcube is a software. So, you should ask the person who installed the software, not it's creator.

**Comment by Chaimadai** [comment]
The person who installed passed away... I just need the link I know my
username and password
my mails are created already I just need to check my mail into roundcube

2017-02-26 21:29 GMT+04:00 Aleksander Machniak <notifications@github.com>:

**Comment by Chaimadai** [comment]
I just need the link so I can sign in... 
Emails and passwords I have them

**Comment by lrosenman** [comment]
We have no way of knowing. We might be able to guess if we know what the
domain name is (the stuff after the @ sign).


On Feb 27, 2017 at 4:05 AM, <Chaimadai <notifications@github.com>> wrote:

I just need the link so I can sign in...
Emails and passwords I have them

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/roundcube/roundcubemail/issues/5669#issuecomment-282678071>,
or mute the thread

**Comment by Chaimadai** [comment]
Domain name is Upcycle.ae

**Comment by rmcaninch** [comment]
This is still not the place for this... Anyhow. The mx records on upcycle.ae point to ovh.net and the IP address for the website belongs to ovh.com Chances are someone at ovh.com can assist you. That's probably who you are paying for the website and email.
