### ISSUE TITLE
Allow line break by pressing Enter, instead of paragraph

### ISSUE THREAD

**Issue by ygoe** [roundcube/roundcubemail#5701]
When pressing the Enter key, I'd like a line break, not a new paragraph with extra padding. I know this might be typographically nicer, but I've also got to deal with other mail clients which do not support this or do not support it nicely so I had to turn it off. When using Roundcube, I always hit Enter twice and get extra much empty space. This should be an option, like it is since it came with Microsoft Word long ago. Thunderbird has that option, too. Outlook doesn't even start with this behaviour.

**Comment by alecpl** [comment]
It is indeed possible to switch this in TinyMCE settings. However, from my experience this mode has some issues. There's a plugin for Roundcube that can be used to enable this mode - https://git.kolab.org/diffusion/RPK/browse/master/plugins/tinymce_config/.

**Comment by Jieiku** [comment]
This plugin appears to work, but not if  the html editor loads by setting 

`$config['htmleditor'] = 1;`

but if I toggle between plain mode and html mode manually then it works. I am assuming it is because the hook never gets attached when the htmleditor is loaded by default in the config...

`$this->add_hook('html_editor', array($this, 'config'));`

I am wondering what other events I can possibly hook on, I am investingating this now, but if you have an idea I can try I would appreciate it.
