### ISSUE TITLE
public_html folder to be used as document root?

### ISSUE THREAD

**Issue by smares** [roundcube/roundcubemail#5707]
The documentation is not quite clear if the public_html folder should be used as document root or not. If yes, there is no symlink pointing to the installer.

**Comment by alecpl** [comment]
It's because it's optional. The installer is to be removed after installation, so I'm not sure we should add the symlink there.

**Comment by thomascube** [comment]
The `public_html` folder was added as an "experimental" feature but is actually the better way to set up Roundcube in order to protect access to the config and other folders. However, it makes the installation a bit more complex and it's mainly useful when running Roundcube as a virtual host.

I agree that documentation about this is entirely missing and maybe its time to fix this. I'm not yet sure whether the installer should be symlinked in `public_html` or the instructions should more be like

> set document root to `<Roundcube install path>`, then run the installer and after finishing, change the document root to `<Roundcube install path>/public_html`

**Comment by alecpl** [comment]
I added a note to INSTALL. Feel free to update the wiki.
