### ISSUE TITLE
sometimes attachment icon is missing

### ISSUE THREAD

**Issue by rc-pl** [roundcube/roundcubemail#5715]
Hi.
I use 1.3-beta with no plugins.
There are cases, where attachment icon is not shown on the message list.
Please check screenshot
![rc2](https://cloud.githubusercontent.com/assets/24810145/24547594/ea7e526c-1610-11e7-97de-5b0b623a5aab.jpg)
Let me know if you need more specific info  for nailing down this case.

**Comment by alecpl** [comment]
This depends on the message Content-Type header. We can use only headers to recognize messages with attachments. Any other solution would require fetching more information from IMAP and would be too slow. With enabled caching we could probably update the state when a message is being open (where we do some extended message structure parsing), but still it wont work without caching.

That's why we closed such requests as won't fix in the past and we do now.

ps. what's the Content-Type for this message?

**Comment by rc-pl** [comment]
Content type header is:

Content-Type: multipart/related;
	boundary="----=_NextPart_000_000B_01D2A3F9.6693C470"

Please comment on this.

**Comment by alecpl** [comment]
According to RFC2387 "The Multipart/Related media type is intended for compound objects consisting of several inter-related body parts". I think it's common use is for HTML messages with inline images, which aren't listed on the attachments list.

Because of that we do not display an attachment icon for multipart/related messages.
