### ISSUE TITLE
Session implementation

### ISSUE THREAD

**Issue by EoleDev** [roundcube/roundcubemail#5790]
Hi,

First of all, i want to thank you for the development of RoundubeEmail.
The product is really amazing, and easy to hack.

On my way into the code, i tried to understand how the session are managed by Roundcube.
I understand quite a bit, but i can't understand how the lifetime works despite the comment: 
"valid time range is now - 1/2 lifetime to now + 1/2 lifetime" rcube_session.php:566

May i have some explanation about it?

**Comment by alecpl** [comment]
The comment is for `$now` property which is used in `check_auth()` method. Generally we account for a situation when session/auth cookies are lost sometimes because of connection issues, or keep-alive requests that may sometimes fail.

I agree the session handling is not the clearest part of the whole system. There are some things like use of two cookies that I'd like to get rid of but never got enough time/inclination to work on this.

**Comment by EoleDev** [comment]
Thanks your answer.
I don't really understand why you set the lifetime of the cookies to be valid 1/2 lifetime before its creation.
I didn't recall to be connected to a system x times before my connection ;)
best regards,
