### ISSUE TITLE
Add internal image proxy to avoid mixed HTTPS content

### ISSUE THREAD

**Issue by shr3k** [roundcube/roundcubemail#5996]
Some HTML messages come with linked HTTP images, these links should be overwritten and routed to an internal image proxy if this message is displayed and then removed again when forwarded/replied to prevent mixed content warnings in the browser. For example, XenForo offers similar functionality.

**Comment by alecpl** [comment]
Browsers display the warning for a reason. I'm not sure we should do this. Write a plugin.

**Comment by evandrofisico** [comment]
To whom it may concern,
I just published a plugin for proxying linked images, using the [imageproxy](https://github.com/willnorris/imageproxy) server. The plugin can be found here: https://github.com/evandrofisico/roundcube-imageproxy

**Comment by alecpl** [comment]
@evandrofisico Could you register it on https://plugins.roundcube.net, please?

**Comment by dddns** [comment]
Howdy,

@alecpl and @evandrofisico would it be possible to make this plugin an roundcube official?
Why that? just because we are in an HTTPS era, and makes all sense to have it in the main RC.

What do you say @alecpl ?

**Comment by evandrofisico** [comment]
> Howdy,
> 
> @alecpl and @evandrofisico would it be possible to make this plugin an roundcube official?
> Why that? just because we are in an HTTPS era, and makes all sense to have it in the main RC.
> 
> What do you say @alecpl ?

Possible, yes, but it adds other dependencies to a roundcube instalation (the imageproxy). I intend to publish it soon, still has some bugs on forwarded messages.

**Comment by dddns** [comment]
Cool, i'll want for it!

**Comment by AndreasSchantl** [comment]
Any updates on this @evandrofisico ?

**Comment by infogulch** [comment]
I would like this feature to proxy all remote resources because that would allow setting the "Allow remote resources (images, styles)" to "always" without compromising mail client privacy.

This has some precedent way back in 2013 when Gmail enabled the feature - ["Images Now Showing"](https://gmail.googleblog.com/2013/12/images-now-showing.html) (and even before that in Yahoo Mail apparently), which basically proxies resource requests to prevent leaking details about your client. More recently, even Apple is getting in on the action: ["Apple Putting a Stop to Email Tracking Pixels With Mail Privacy Protection in iOS 15 and macOS Monterey"](https://www.macrumors.com/2021/06/10/ios-15-mail-privacy-protection-tracking-pixels/)

Honestly I think a feature like this should be a high priority for anyone that cares about the privacy of their normal users who don't/won't/shouldn't care about why loading remote resources from client devices is a bad idea.... by making it not a bad idea anymore because the resources are proxied and cached. As a bonus this feature means that users don't need to be nagged about images every time they open an email. (In fact I'd prefer if resources were *pre*-cached as soon as the email arrives so that even first open time is not exposed to the sender.)
