### ISSUE TITLE
What about Roundcube Next?

### ISSUE THREAD

**Issue by gjsman** [roundcube/roundcubemail#6030]
Two years ago now, Roundcube raised over $100,000 for "Roundcube Next", then promptly abandoned it taking all the money, without any explanation.

https://github.com/roundcube-next

Explanation please.

**Comment by thomascube** [comment]
There are a few mistakes to clarify: the Roundcube Next crowdfunding was not done by Roundcube but by Kolab Systems. It was meant to become a successor for Roundcube and therefore we helped promoting it and also added helped in the early stages of conception and prototyping. Anything that goes beyond is the sole responsibility of Kolab Systems and can only be explained by them. Despite the naming, there's no relation between the two projects and thus this ticket was opened in the wrong place.

**Comment by MagicFab** [comment]
According to Phoronix, [not happening](https://www.phoronix.com/scan.php?page=news_item&px=RoundCube-Next-2018).

**Comment by mpass3** [comment]
thomascube, weren't you the last person to update the Roubdcube Next indigogo page? To say that you have no responsibility for it is a little rich. Shouldn't the money be returned to the backers?

**Comment by mckaygerhard** [comment]
jajaj seems was a "hack" of money!

**Comment by mckaygerhard** [comment]
issue #7110 was closed... no explanations, we only request some information ...

**Comment by zainjetha** [comment]
This is only due to sheer cowardness of @alecpl and @thomascube 
 
And of course @kanarip

**Comment by zainjetha** [comment]
Whilst you state there is no relation between the projects, one of you @alecpl  is very involved with Kolab Systems. 

@thomascube You claim there is no link between the projects, except the name. Except for you are seen discussing it with Georg Greve and you were hired by them until you resigned, and would've otherwise closely been involved.

@Alecpl has denied being employed by Kolab Systems, though he does a large amount of development work for them as can be seen on their Phabricator instance. This could be a lie.

If this was a planned successor to Roundcube (I note that the link on roundcube.net) has been removed, why would you decline to ask @kanarip to do the honourable thing and encourage comment.
Irrespective of responsibility, undeniably it looks bad on Roundcube - and it can only be termed cowrdice when one has the power to act, but conveniently chooses to ignore the situation @thomascube @alecpl

**Comment by zainjetha** [comment]
Further, please see confirmation that @alecpl is a liar.

![Screenshot 2020-01-15 at 22 46 21](https://user-images.githubusercontent.com/58792618/72478063-fc1e3580-37e8-11ea-9433-ccd5d114462c.png)

![Screenshot 2020-01-15 at 22 46 21](https://user-images.githubusercontent.com/58792618/72478119-2243d580-37e9-11ea-9be2-44f9f2a88880.png)

I believe that this means @alecpl is an employee of Kolab Systems therefore his comment on task #7110 (now closed) is at least more than partially untrue.

@kanarip speak up

**Comment by zainjetha** [comment]
Further confirmation by @alecpl that he 'works for' Kolab Systems on his own blog is here
![Screenshot 2020-01-15 at 22 46 21](https://user-images.githubusercontent.com/58792618/72478358-b7df6500-37e9-11ea-814a-a56bd59c54a9.png)

**Comment by mckaygerhard** [comment]
OWOWW! that's was a big noted!

**Comment by alecpl** [comment]
I removed offensive comments from the user known from such behaviors. His statements were not true and based on outdated information. I'm no longer an employee of Kolab Systems and I was never directly involved in Roundcube Next.

**Comment by thomasdotklein** [comment]
It is worth clarifying that Kolab Systems is now Apheleia IT AG limited.

Thus, all Kolab Systems employees are essentially Apheleia employees.

@alecpl as Roundcube Next was going to replace Roundcube 1, and the limitations in developing it further (even if developed by Kolab [Apheleia])  it may be a little unfair to say the Roundcube developers had no interest in this, given that Aleksander develops actively for Kolab.

It is also noteworthy Kolab´s requirements are likely to have a significant influence on  Roundcube development roadmap, given they are the biggest sponsor of Roundcube.

@alecpl I would respectfully ask you to do what you can to help an update be given by Apheleia leadership. Your development role in Roundcube and it being Kolab´s webclient means your views would likely be considered.

As you develop Roundcube, I am sure you would have thoughts on whether it makes sense to add more features, and when the point of adding new features starts to yield diminishing returns because of the cost of development and deep structural changes.

**Comment by SolarDesalination** [comment]
Thanks for the update @alecpl I'll make sure to update the Wikipedia article about that company. I find it interesting that they would change their name to try to get away from the fact that they stole $100,000 from crowdfunders.

**Comment by alecpl** [comment]
Here's my position:

@thomasdotklein also known as @zainjetha is a stalker and a liar. I'd be careful with using information from him.

@thomascube already clarified what had happened. This is a wrong place for this conversation.

Kolab Systems still exists so it could not change the name. None of Kolab Systems' owners and management is with Aphelia IT. Yes, it took over some employees and services, and is working on Kolab, but that's it.

**Comment by thomasdotklein** [comment]
@alecpl please note I am not affiliated with anybody. My goal is to get a meaningful response, not hearsay.

_Dear Customer

We are happy to announce that we found a new home under Apheleia IT AG.

Kolab Systems AG, the company behind Kolab Now is closing down for reasons unrelated to Kolab Now. Apheleia IT AG have been long time partners of Kolab Systems AG and will continue the Kolab Now business with the same team that provided Kolab Now to you before.

What this means for you:

Service will continue as usual
We keep the promises that we made about privacy and security of your data
The company name will change on our Terms of Service
Apheleia IT AG is based in Switzerland as well, so there will be no change in jurisdiction
Your data will be handled by the same team - and ONLY those people - who handled your data securely through the years
The move to Apheleia IT AG will allow our team to focus on moving Kolab Now forward and provide you with new features and improvements. You have seen the first results of this already, when we rolled out the new and improved responsive skin as the default skin, which makes our web client usable on your mobile devices and comes with a bunch of other improvements, as well as the refresh of the Kolab Now website.

We hope that you will recognize the effort that the team is -and has put into protecting your collaboration data and communication, and that you still like and love Kolab Now under the new roof.

You do not have to take any action In order to be able to continue to use all Kolab services and to benefit from all advantages. Should you have any remarks or objections, they can be addressed directly to the support department (support@kolabnow.com) according to our terms of service.

We thank you in advance for your continued trust, and will do our utmost to live up to it.

Sincerely

The Kolab Now Team

Dear Thomas,

As you can read in the earlier in this ticket, there is one company. It is called Apheleia IT AG. You are a customer of that company by having a subscription to the service Kolab Now.

We will make sure to correct any misunderstandings that may have existed internally at the earliest opportunity.

That should answer all your questions.

Sincerely

Mads Petersen
Kolab Now Support_

From the included correspondence, it seems clear that Kolab Systems is closing down and therefore does not exist anymore. This is in contrast to @alecpl is saying, so please note I have not lied, but gone on factual information been provided.
Given the discrepancy information, there is likely a misunderstanding of sorts.

Dreamlab Technologies AG Zurich confirmed they now own Apheleia (previously DreamLab).

**Comment by alecpl** [comment]
Kolab Now is a service that was took over by Apheleia IT, that's it. Please, do not read between the lines and imply things you have no full knowledge about.

I cannot lock this ticket, but I can delete comments and I will. This is not a proper place for this discussion. Acknowledge that you'll get no more details from me or Thomas on this subject.

**Comment by thomasdotklein** [comment]
@alecpl whilst I understand this issue was not of yours and @thomascube making (nobody said it was) all I would request is that you speak to the decision makers.

In the absence of hard facts (though most are factual, and no ´reading between the lines has occurred´ too much) logical conclusions should be drawn. Particularly when nobody is inclined to speak up.

I think we can conclude this is not an ideal situation by any means, and it should be understandable that people will seek ways to get answers (whether appropriate channels are used or not) particularly when the appropriate channels and methods have failed.

**Comment by SolarDesalination** [comment]
> Please, do not read between the lines and imply things you have no full knowledge about.

@alecpl states that the public doesn't have full knowledge on the loss of $100,000 USD of altruistic FOSS supporters funds. He works for the company that took those funds. He states he was not working on the project, which is all fine and well but, he states that "we shouldn't speak to something we don't have full knowledge about." Which is an admission that he does know more about where the funds went. (What I can only surmise is an attempt to clear his conscience and maintain purity of his day to day work), he states that the Roundcube project; whose developers are paid by Kolab Systems/Apheliea IT which provided branding and project support to Roundcube Next, is not associated with Roundcube. Meanwhile in order to stop questions he threatens to delete comments that aren't related to the Roundcube project; despite not providing an alternate venue to get a public response from the small firm that he works for that took the FOSS-supporters funds and provided nothing in return.

@thomascube who provided the last update on the RoundCube Next IndieGogo project page, ignores the conversation and states that despite being one of the fund site's maintainer, he had nothing to do with the project.
![image](https://user-images.githubusercontent.com/51060565/87303591-6df9e200-c4e1-11ea-9748-96cd063ea4ec.png)

I'll screenshot this comment because I'm sure @alecpl will delete it. I'd only further state that until there is an update from Apheliea IT on the crowdfunds of RoundCube Next, you can delete comments but the Roundcube project will be forever associated with disappearing $100,000 of FOSS supporter money with nothing to show for it. I'm sure most supporters have moved on but it's quite unethical in my opinion.

**Comment by SolarDesalination** [comment]
Not sure how you sleep at night man.

**Comment by thomasdotklein** [comment]
In the interest of free speech - please see @SolarDesalination comment re-pasted and thus restored.
When countries like Hong Kong are losing their freedom because of authoritarian leadership who fail to allow freedom of speech, the same should most not certainly apply here [on a public channel]
 
@alecpl states that the public doesn't have full knowledge on the loss of $100,000 USD of altruistic FOSS supporters funds. He works for the company that took those funds. He states he was not working on the project, which is all fine and well but, he states that "we shouldn't speak to something we don't have full knowledge about." Which is an admission that he does know more about where the funds went. (What I can only surmise is an attempt to clear his conscience and maintain purity of his day to day work), he states that the Roundcube project; whose developers are paid by Kolab Systems/Apheliea IT which provided branding and project support to Roundcube Next, is not associated with Roundcube. Meanwhile in order to stop questions he threatens to delete comments that aren't related to the Roundcube project; despite not providing an alternate venue to get a public response from the small firm that he works for that took the FOSS-supporters funds and provided nothing in return.

@thomascube who provided the last update on the RoundCube Next IndieGogo project page, ignores the conversation and states that despite being one of the fund site's maintainer, he had nothing to do with the project.
image

I'll screenshot this comment because I'm sure @alecpl will delete it. I'd only further state that until there is an update from Apheliea IT on the crowdfunds of RoundCube Next, you can delete comments but the Roundcube project will be forever associated with disappearing $100,000 of FOSS supporter money with nothing to show for it. I'm sure most supporters have moved on but it's quite unethical in my opinion.

**Comment by thomasdotklein** [comment]
@alecpl states that the public doesn't have full knowledge on the loss of $100,000 USD of altruistic FOSS supporters funds. He works for the company that took those funds. He states he was not working on the project, which is all fine and well but, he states that "we shouldn't speak to something we don't have full knowledge about." Which is an admission that he does know more about where the funds went. (What I can only surmise is an attempt to clear his conscience and maintain purity of his day to day work), he states that the Roundcube project; whose developers are paid by Kolab Systems/Apheliea IT which provided branding and project support to Roundcube Next, is not associated with Roundcube. Meanwhile in order to stop questions he threatens to delete comments that aren't related to the Roundcube project; despite not providing an alternate venue to get a public response from the small firm that he works for that took the FOSS-supporters funds and provided nothing in return.

@thomascube who provided the last update on the RoundCube Next IndieGogo project page, ignores the conversation and states that despite being one of the fund site's maintainer, he had nothing to do with the project.
image

I'll screenshot this comment because I'm sure @alecpl will delete it. I'd only further state that until there is an update from Apheliea IT on the crowdfunds of RoundCube Next, you can delete comments but the Roundcube project will be forever associated with disappearing $100,000 of FOSS supporter money with nothing to show for it. I'm sure most supporters have moved on but it's quite unethical in my opinion.

**Comment by thomasdotklein** [comment]
@alecpl states that the public doesn't have full knowledge on the loss of $100,000 USD of altruistic FOSS supporters funds. He works for the company that took those funds. He states he was not working on the project, which is all fine and well but, he states that "we shouldn't speak to something we don't have full knowledge about." Which is an admission that he does know more about where the funds went. (What I can only surmise is an attempt to clear his conscience and maintain purity of his day to day work), he states that the Roundcube project; whose developers are paid by Kolab Systems/Apheliea IT which provided branding and project support to Roundcube Next, is not associated with Roundcube. Meanwhile in order to stop questions he threatens to delete comments that aren't related to the Roundcube project; despite not providing an alternate venue to get a public response from the small firm that he works for that took the FOSS-supporters funds and provided nothing in return.

@thomascube who provided the last update on the RoundCube Next IndieGogo project page, ignores the conversation and states that despite being one of the fund site's maintainer, he had nothing to do with the project.
image

I'll screenshot this comment because I'm sure @alecpl will delete it. I'd only further state that until there is an update from Apheliea IT on the crowdfunds of RoundCube Next, you can delete comments but the Roundcube project will be forever associated with disappearing $100,000 of FOSS supporter money with nothing to show for it. I'm sure most supporters have moved on but it's quite unethical in my opinion.

**Comment by HLFH** [comment]
Between Switzerland and the EEA, you have the [Lugano Convention](https://en.wikipedia.org/wiki/Brussels_Regime#Lugano_convention_(2007)) (2007).
With [rewards-based crowdfunding](https://ec.europa.eu/growth/tools-databases/crowdfunding-guide/types/rewards_en), **you are obliged to deliver the service or the goods promised on schedule**.
Nothing has been delivered so far.
Roundcube Next rewards-based crowdfunding campaign was a fraud, and every backed is entitled to be refunded.

Do not hesitate to contribute to this repository that is not censored: https://github.com/HLFH/Roundcube-Next-Fraud, to help the backers answer the following questions:

**- Who to sue?**

**- How to sue?**

**- Until when you can sue?**

**Comment by thomascube** [comment]
Again: this is not a Roundcube issue.
The only suggestion I have for all of you: **don't feed the trolls**!
