### ISSUE TITLE
stopping multiple executions of same JS event

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#6192]
in common.js rcube_event_engine::triggerEvent(), around like 382, returns from the events are handeled like this:
```js
// cancel event execution
if (ret !== undefined && !ret)
  break;
````
but I think may be it should be:
```js
// cancel event execution
if (ret !== undefined)
  break;
````
Lets say you have 2 plugins both attach an event to the `rcube_list_widget::getselection event`. The first plugin returns a section but hook execution continues and the second plugin has no return. The end result is no return since execution is only stopped if false/null is returned.

This could be a special case for the getselection for type events where there is only a return in specific cases (when that plugin wants to do it thing). I've had a look through the core plugins and I don't think this change would break anything.

**Comment by thomascube** [comment]
Event abortion is only meant to happen if one handler returns `false` and that behavior should not be changed. The event system is actually not designed to collect return values from handlers at all. With multiple handlers assigned, the correct way to handle return values would be to return an array containing the return values of all handlers. For this particular situation, I suggest to not use the return value of `this.triggerEvent('getselection'`) but instead pass an array reference for the resulting selection as an argument. This way, each event handler can add items to the selection and if one handler thinks it has the final say, it can return `false` in order to stop propagation. For `list.js` the change could be as follows:

```js
  var res = $.merge([], this.selection);
  if (this.triggerEvent('getselection', deep, res) === false)
    return res;
```

**Comment by johndoh** [comment]
looks good. I think you can only pass 1 param to triggerEvent though so may be:
```js
var props = {deep: deep, res: $.merge([], this.selection)};
if (this.triggerEvent('getselection', props) === false)
  return props.res;
```

**Comment by alecpl** [comment]
Looks good. Mind creating a PR?

**Comment by alecpl** [comment]
Done.
