### ISSUE TITLE
Duplicate key value for session_pkey

### ISSUE THREAD

**Issue by acheronmedia** [roundcube/roundcubemail#6240]
I'm having problems which looks similar to those in issue #3588, however this is Roundcube 1.3.5, running with PostgreSQL 9.6 backend, on PHP 7.0.29. (FreeBSD). I see sporadic errors logged about duplicate key value for `session_pkey`.

Session ID and value sanitized with _XXX_:

```
Apr  9 13:49:27 <local0.warn> postgresql postgres[89767]: [9-1] ERROR:  duplicate key value violates unique constraint "session_pkey"
Apr  9 13:49:27 <local0.warn> postgresql postgres[89767]: [9-2] DETAIL:  Key (sess_id)=(b915_XXX_rpv5) already exists.
Apr  9 13:49:27 <local0.warn> postgresql postgres[89767]: [9-3] STATEMENT:  INSERT INTO "session" ("sess_id", "vars", "ip", "changed") VALUES ('b915_XXX_rpv5', 'dGVtc_XXX_UiI7', '<client  IPv4>', now())
```

Corresponding access log (client subdomain censored):

```
<client IPv4> - - [09/Apr/2018:13:49:27 +0200] "GET /?_task=mail&_action=list&_refresh=1&_mbox=INBOX&_remote=1&_unlock=loading1523274567480&_=1523274567213 HTTP/2.0" 200 180 "https://XXXX.irealone.com/?_task=mail&_mbox=INBOX" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "-"

<client IPv4> - - [09/Apr/2018:13:49:27 +0200] "GET /?_task=mail&_action=getunread&_page=1&_remote=1&_unlock=0&_=1523274567214 HTTP/2.0" 200 161 "https://XXXX.irealone.com/?_task=mail&_mbox=INBOX" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "-"
```

The error appears on first request after some time has passed (hours), so I'm guessing due to the session being expired. I've checked all the occurrences, they're all the same - first request after a (longer) while.

**Comment by alecpl** [comment]
What were the other http requests from this client before that happened? This looks strange as if the session expired it should not just create a new one without login action. Maybe the session did not really expire, but the code was fouled to think so and did insert instead of update. Anyway, that might be hard to investigate.

**Comment by sergiokessler** [comment]
same here:
`ERROR:  duplicate key value violates unique constraint "session_pkey"`
every now and then...

**Comment by alecpl** [comment]
Not enough information. Please, re-test with 1.4.

**Comment by dminuoso** [comment]
We encounter this problem regularly once an hour or so, but because it's with a large number of users it individually occurs rarely.

We use the `db` driver (though judging from what I've seen I don't think this to be relevant - if a different driver appears to solve it, it's probably because the timings behind the race conditions just change.

Necessary preconditions:
- Session expiry be enabled
- Enough PHP FPM workers to allow for concurrent processing 
- A previous session for a user exists but is expired
- The website is refreshed some way

At times two simultaneous inserts into the sessions table are done, but at other times not.

@alecpl Are you fine with re-opening this issue? I am willing to provide further information or insert further debugging logs until this is resolved.

**Comment by dminuoso** [comment]
On a second note, it's quite likely the problem is only visible with the `db` driver interface because of the NOT UNIQUE constraint on the session id.
