### ISSUE TITLE
Elastic: check compiled css files into git

### ISSUE THREAD

**Issue by thomascube** [roundcube/roundcubemail#6284]
This would make it easier to deploy Roundcube without having `lessc` installed on the target machine. I suggest to move the `.less` files into a `src` folder and push the built CSS files with each change. That's quite common for libraries that need to be built (e.g. node modules) and still allows one to customize the skin using the source files.

**Comment by alecpl** [comment]
Sounds cumbersome, especially when we'll have multiple branches.

**Comment by thomascube** [comment]
It's common practice, especially for npm modules to have both the sources and the built version checked in. Also works with branches ;-)

**Comment by binarykitchen** [comment]
I agree, I do not want to install node on the server only because of this.

**Comment by binarykitchen** [comment]
Since this is PHP, why not install https://github.com/wikimedia/less.php? It has the same command. 
See https://github.com/wikimedia/less.php#command-line

**Comment by alecpl** [comment]
@imrejonk I don't plan to support tools like this. Looks like this is the main issue: https://github.com/lesscpy/lesscpy/issues/71, and lesscpy does not look like an actively maintained project.

**Comment by imrejonk** [comment]
I wasn't aware that lesscpy doesn't support `@import` statements, which to me seems like an essential feature. Looks like there is no useable Less compiler at all in the Red Hat 8 repositories :(

**Comment by floriangosse** [comment]
I think checking in compiled files into repositories should be avoid all the time. To do so you always have to keep in mind to compile the files every change you make and it can make merging pull requests that change the stylesheets way harder because of possible merge conflicts.

I propose to provide deployable archives that contain the relevant files. This allows administrators to setup the the application without having to build parts of it before it will be deployed. I think providing these files should be relative easy in the first step as it could be automated.
