### ISSUE TITLE
global "mark all folders as read" does not update folder unread messages count label #6270

### ISSUE THREAD

**Issue by grape6** [roundcube/roundcubemail#6307]
described in #6270

Seems this happens for any folder except INBOX.

Can be reproduced in that way: mark some messages as unread in any other folder (tmp), log out,
log in, select another folder (arch), mark all messages as read, and for (tmp) folder count label is not updated.

RCM git, only contextmenu plugin is enabled.

**Comment by alecpl** [comment]
Still works for me. Any errors in browser console? Could you check response of the ajax request? Could you enable imap_debug and provide the log?

**Comment by johndoh** [comment]
The problem seems to be related to `$_SESSION['unseen_count']` its NULL. Debug shows the unseen_count being populated for each folder during login but then its nulled.

It means in rcmail_send_unread_count `$unseen != $old_unseen` is `0 != null` which is false so the set_unread_count command is not set for anything accept inbox.

I checked and the unseen_count is removed from the session but I cannot find where :/

running git-master all plugins disabled.

**Comment by johndoh** [comment]
problem occurs with `session_storage` 'db' but not 'php'

**Comment by alecpl** [comment]
Thanks @johndoh that helped. There are `list` and `getunread` ajax request when Mail UI is displayed. I was able to reproduce the issue if I make the `list` request to take longer and finish after `getunread`.

**Comment by alecpl** [comment]
Fixed.
