### ISSUE TITLE
message_before_send Arguments: mailto is not an array

### ISSUE THREAD

**Issue by hansmaulwurf23** [roundcube/roundcubemail#6353]
Using the hook `message_before_send` we fetch the mailto via
```php
$recipientCount = count($args['mailto']);
```
which is not working. More evaluation led us to
```php
is_array($args['mailto'])
```
which returns false. Are we using the args in a wrong manner or is the wiki outdated?

**Comment by alecpl** [comment]
If you use only Bcc header it can be also a string "undisclosed-recipients:;". Is this the case?

**Comment by alecpl** [comment]
Ok, I see it's also a string for other cases. The confusion comes from rcube::deliver_message()'s 3rd argument description. That argument is described as an array, but it looks like it also works with a string.
Maybe it's like that for historical reasons or maybe it's because we pass that argument to rcube_smtp::send_mail() which accepts both. From what I see we always use a string input.

Anyway, that argument should be described as "Either a comma-separated list of recipients (RFC822 compliant), or an array of recipients, each RFC822 valid".

**Comment by alecpl** [comment]
Fixed.

**Comment by hansmaulwurf23** [comment]
Thanks a lot for the quick reply and fix!

**Comment by javabytemon** [comment]
> FYI. You can extract recipient addresses using `rcube_mime::decode_address_list($args['mailto'], null, false, null, true)` and then count them.

When I perform this task it works great and gives me the total number of items in the array. Now I want to print out each array item. Using simple foreach loop does not show the email addresses in the array.
e.g
`$emails = rcube_mime::decode_address_list($args['mailto'], null, false, null, true);
 foreach($emails as $email){
  rcube::write_log('something', $email);
}
`
I get a warning about converting an array to string. Does it mean $email is a 2 or 3D array. If so what are the indexes.
