### ISSUE TITLE
Cannot add attachments - file exceeds max PHP attachment size - bug?

### ISSUE THREAD

**Issue by RickD123** [roundcube/roundcubemail#6459]
Hi,

I seem to have found a bug in RC 1.3.7 and 1.4 beta. When trying to add any attachment of any size I basically get an error message saying that the file I am trying to upload exceeds the PHP max upload size. Then when updating the max upload size (e.g. to 50 MB) then I still get the same error message when trying to upload a small text file (of course I restarted my Apache 2.4 before). Any ideas? I tried with the no_sniff parameter and both Safari and Chrome on Mac, no luck so far. Any ideas? There is nothing in the Apache, Postfix nor RC logs...

Kind regards
Sebastian

**Comment by alecpl** [comment]
Note there are two options in PHP: upload_max_filesize and post_max_size. Also, it can be set via php.ini as well as .htaccess file. Also, make sure you restart the process after updating php.ini.

I don't see a bug here.

**Comment by RickD123** [comment]
I would like to reopen this if possible. Here is my Apache config for the vhost running Roundcube:

php_value error_reporting -1
php_value display_errors 1
php_value display_errors On
php_value suhosin.session.encrypt Off
php_value upload_max_filesize 50M
php_value post_max_size 50M
php_value memory_limit 4096M
php_value max_execution_time -1
php_value upload_tmp_dir /var/www/webmail.mydomain.tld/tempdir

These settings used to work for years now with 1.3.7 and 1.4 beta it does no longer. Any ideas?

Kind regards
Sebastian

**Comment by RickD123** [comment]
As I mentioned, there is no message in the log files of Roundcube. Adding an attachment just does not work despite the fact that the tempdir directory of Roundcube is writable for the user running Apache. Any ideas?

**Comment by merilturock** [comment]
I agree with RickD123: I am not able to attach more than 1 MB while my upload limit is set 15 MB.. My php.ini is perfecly configured where there is an another website within the server which is able to upload up to 20 MB while roundcube doesn't ..  This is a biggest error where round cube doesn't even care to address this plz google every forum has this bug mentioned & people have not got a single solution for this..

![roundcube error](https://user-images.githubusercontent.com/1689530/56682262-d1cf9980-66e8-11e9-8998-d78110d284fa.PNG)
![roundcube error 1](https://user-images.githubusercontent.com/1689530/56682266-d431f380-66e8-11e9-96fd-20af148115d7.PNG)

**Comment by m-ueberall** [comment]
@merilturock: _"doesn't even care to address this"_ sounds a bit harsh.
@RickD123: I managed to upload a 15 MB attachment w/o problems, so I suspect it's a configuration error on your end. You listed the ``php.ini`` settings, but did you have a look at the session storage related settings in ``config.inc.php`` as well?
If you use ``$config['session_storage'] = 'memcache'``, for example, you need to ensure that ``$config['memcache_max_allowed_packet'] = 16*1024*1024`` matches the expected maximum attachment size (the same goes for ``apc`` or ``redis``); this is actually documented in ``defaults.inc.php``.

**Comment by merilturock** [comment]
@m-ueberall: I am not trying to be rude i am just saying that this problem is real & it needed to be addressed or at least make the configuration part much simple too much of configuration can make an app really messy & not usable as this App has lot of potential but just bcz of some simple upload stuff it's getting really harder for the end user.. Now check on my config i don't know what to do much more to make my upload to just cross beyond 1MB ..
![php ini file](https://user-images.githubusercontent.com/1689530/56823095-8ea03280-6870-11e9-8806-06049cf764c3.PNG)
![roundcube setting 1](https://user-images.githubusercontent.com/1689530/56823131-a677b680-6870-11e9-9b9f-63e6378e6110.PNG)
![roundcube setting 2](https://user-images.githubusercontent.com/1689530/56823132-a677b680-6870-11e9-91d2-4bd21b67cc73.PNG)
![roundcube setting](https://user-images.githubusercontent.com/1689530/56823134-a7104d00-6870-11e9-85b0-bf209e47a15f.PNG)
![roundcube htaccess](https://user-images.githubusercontent.com/1689530/56823152-b099b500-6870-11e9-8f35-88cb04ec2f6e.PNG)

I have attached all my configuration & i still don't have any luck crossing my upload MB more than 1MB..
the plugin's enabled ..

// List of active plugins (in plugins/ directory)
$config['plugins'] = array('acl', 'additional_message_headers', 'archive', 'attachment_reminder', 'database_attachments', 'emoticons', 'enigma', 'filesystem_attachments', 'help', 'hide_blockquote', 'http_authentication', 'identicon', 'identity_select', 'jqueryui', 'managesieve', 'markasjunk', 'newmail_notifier', 'password', 'virtuser_file', 'virtuser_query', 'zipdownload');

**Comment by alecpl** [comment]
What do you see in Roundcube error log? Having two attachment plugins is not supported and will just not work.

**Comment by merilturock** [comment]
@alecpl : *Having two attachment plugins is not supported and will just not work.
Removed one of the attachment plugin now it works .. I guess an error warning msg or conflict msg should be provided .. 

There is no error logged in the error log of Roundcube ..
