### ISSUE TITLE
fail2ban: Stop refreshing when login fails

### ISSUE THREAD

**Issue by vpelletier** [roundcube/roundcubemail#6474]
I have a fail2ban setup to watch roundcube log for authentication failures (in addition to built-in login rate limiter), and users can change their IMAP password without having to go through roundcube. When they do and they have roundcube open in a tab, they promptly get detected as a bruteforce attempt and banned.

I think auto-refresh should stop and display an error (maybe send user to login form ? not sure how it would play if user is composing an email right at that time) on the first authentication error.

**Comment by alecpl** [comment]
I agree we should display an error. As the imap authentication failure may be temporal and we do not know it's caused by a new password, I would not logout the user.

**Comment by alecpl** [comment]
Done.

**Comment by vpelletier** [comment]
I am not sure the issue if completely resolved: while displaying the error is an improvement, the main issue for me is that users trigger fail2ban "without doing anything", just by having a tab opened somewhere when they change their password.

Unless I'm misreading the patch, or if there is another patch, it seems roundcube will keep refreshing even if there is an error. This may require distinguishing between "credentials received and rejected" and other errors ("browser-server network error", "server internal error" like "couldn't reach auth DB", ...), which hopefully should be possible (I don't know IMAP, but hopefully they do have separate error codes, similar to HTTP 403).

Now that the error became visible, I think the user can more easily understand they are supposed to do something to get a fresh mailbox view.

**Comment by alecpl** [comment]
We could catch authentication errors, but even these can be caused by different factors. We don't know if it's wrong credentials or some temporary failure on authentication DB. Even if server specifically says "wrong credentials, password changed" there's no standard for this. Correct me if I'm wrong. And I don't think we should stop refreshing on every auth error.

**Comment by thomas-mc-work** [comment]
> We could catch authentication errors, but even these can be caused by different factors. We don't know if it's wrong credentials or some temporary failure on authentication DB. Even if server specifically says "wrong credentials, password changed" there's no standard for this.

From my understanding we are talking about two different situations. First: authentication fails for any technical reasons (as you've stated, this could be e.g. a temporary failure on authentication DB). Second: proper authentication failures due to invalid credentials.

My question is here: Can these two situation be distinguished properly by the IMAP status code? I only know HTTP. There the situation is very clear: You receive a `401` if and only if the credentials are invalid. Any other server side errors return a `5xx` status code, client side errors a `4xx`.

For the second scenario: In this case I think it wouldn't make sense to keep the current session alive. The current credentials are definitely invalid. If the user would logout and login with the same credentials, it would never succeed.

What do you think about that, @alecpl ?

**Comment by alecpl** [comment]
That's what I've said. There's no way to distinguish these two cases on the IMAP protocol level.

**Comment by thomas-mc-work** [comment]
What about this section from the RFC?:

> 535 5.7.8  Authentication credentials invalid
>
>   This response to the AUTH command indicates that the authentication
>   failed due to invalid or insufficient authentication credentials.  In
>   this case, the client SHOULD ask the user to supply new credentials
>   (such as by presenting a password dialog box).

**Comment by alecpl** [comment]
This is SMTP, not IMAP. So, it would only work when you actually tried to send an email.
