### ISSUE TITLE
IMAP: Wrong startup greeting

### ISSUE THREAD

**Issue by neo0nymous** [roundcube/roundcubemail#6571]
So i followed a tutorial from the web and apparently now this appears. 

`[24-Dec-2018 00:56:51 +0100]: <qm31qvst> IMAP Error: Login failed for admin@censored.xyz from MY.IP.CENSORED Wrong startup greeting (127.0.0.1:143): * BYE Disconnected: Auth process broken in /var/www/html/roundcube/program/lib/Roundcube/rcube_imap.php on line 196 (POST /roundcube/?_task=login&_action=login)`

**Comment by alecpl** [comment]
Something's wrong with the imap server. Does it work with other clients? Try `telnet 127.0.0.1 143`.

**Comment by neo0nymous** [comment]
I tried it i get this :/ `could not resolve 127.0.0.1:143/telnet: Name or service not known`

**Comment by neo0nymous** [comment]
Ok i resolved it, it was a problem with dovecot, you need to extra declare the database driver.

**Comment by nigel-aves** [comment]
neo0nymous - I have run into the same issue, but I don't understand your comment " it was a problem with dovecot, you need to extra declare the database driver. " ... I'm not an IT person, but if you could explain a little deeper what you did would / might help me. Many Thanks - Nigel.

**Comment by volcano1111** [comment]
> 
> 
> neo0nymous - I have run into the same issue, but I don't understand your comment " it was a problem with dovecot, you need to extra declare the database driver. " ... I'm not an IT person, but if you could explain a little deeper what you did would / might help me. Many Thanks - Nigel.

The first thing you need to do is to check your log files. I don't know what's your setup or system, but I think it would be **syslog** or **mail.log** in **/var/log** directory. I've had the same issue and in my logs I found some errors of this kind: 

> warning: pgsql:/etc/postfix/pgsql/virtual_alias_maps.cf is unavailable. unsupported dictionary type: pgsql

So in my case this was a database connection error. I have a PostgreSQL DB server and Postfix didn't knew about it, because I forgot to install database driver. I ran **apt install postfix-pgsql -y**, then **postfix reload** to apply new settings and now everything run smoothly. I can help if you need any more explanation.
