### ISSUE TITLE
mark as read/unread icons in Elastic

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#6636]
please consider using alternative icons for mark as read/unread in the menu. I think that something like https://fontawesome.com/icons/envelope?style=solid and then https://fontawesome.com/icons/envelope-open?style=solid or may be https://fontawesome.com/icons/envelope-open-text?style=solid might be more intuative than the dots.

**Comment by alexanderdd** [comment]
Please add label "C: Interface" and add it to a milestone.

I haven't tested elastic (dots seem unintuitive!) but on all the old skins there is a **star** to mark read/unread. This is bad UX because most users are used to mark an email/item with a star to show that it is important.
I guess the star originally came into place as inspired from thunderbird, but they use grey/green light as indicators. The star was a bad ux decision that leads to bad ux for thousands of users. Let't try to get it right this time.

**Comment by johndoh** [comment]
@alexanderdd I added this to my `_styles.less`:
```
.toolbarmenu li {
  a.read:before {
    .font-icon-solid(@fa-var-envelope-open-text);
  }
  a.unread:before {
    content: @fa-var-envelope;
  }
}
```

**Comment by alexanderdd** [comment]
@johndoh can you make a pull request to change the elastic skin like you are using it? 
I like the icons.

**Comment by johndoh** [comment]
I think this is a topic for discussion rather than something clear cut. So for now I suggest people :+1: if they like my idea or add their own ideas.

**Comment by alecpl** [comment]
Agreed. Done.

**Comment by bbraybrook-tc** [comment]
hey alec, i think with the other changes to the list this got overridden in 1.4.1.rc2. the lessc for the change is a bit different now with the new styling (and it reverted back to the dot)
