### ISSUE TITLE
address_book_type='' issue

### ISSUE THREAD

**Issue by alecpl** [roundcube/roundcubemail#6680]
```
/ This indicates which type of address book to use. Possible choises:
// 'sql' (default), 'ldap' and ''.
// If set to 'ldap' then it will look at using the first writable LDAP
// address book as the primary address book and it will not display the
// SQL address book in the 'Address Book' view.
// If set to '' then no address book will be displayed or only the
// addressbook which is created by a plugin (like CardDAV).
$config['address_book_type'] = 'sql';
```
The last description sentence is not true. Setting the option to an empty string will disable sql addressbook, but not ldap addressbook. I'm not sure what was the intention. We should at least correct the description.

@thomascube what do you think?

**Comment by urusha** [comment]
We use both ldap (searchonly) and https://github.com/blind-coder/rcmcarddav addressbooks and also https://github.com/teonsystems/roundcube-plugin-automatic-addressbook-ng
With empty `address_book_type` the sql address book is removed from UI, and this allows to use CardDAV address book as "default" (first) and also use it to add collected contacts with:
`$config['automatic_addressbook_ng_use_addressbook'] = '-1';` see https://github.com/teonsystems/roundcube-plugin-automatic-addressbook-ng/blob/master/config/config.inc.php.dist (`-1` seems to exclude ldap from the addressbook list)
And this part works fine currently.

But since https://github.com/roundcube/roundcubemail/pull/6664 is not applied, in contacts tab the ldap addressbook stays the first. And this leads to switching to the ldap addressbook after search reset, see https://github.com/roundcube/roundcubemail/issues/6679#issuecomment-472448717 (is this expected behavior?)
Suggested kolab_addressbook plugin requires kolab (just tried) and according to https://github.com/dupondje/roundcubemail-plugins-kolab/blob/master/plugins/kolab_addressbook/kolab_addressbook.php
```
 // Assumes that all non-kolab_addressbook sources are global
```
Well, I just want to say that we might need a common way to sort addressbooks (or change default order, since `searchonly` + plugin might be the case).

**Comment by alecpl** [comment]
I told you the order is not a problem here. And searchonly related issues have its own ticket (#6679). I didn't suggest to use kolab_addressbook, I just pointed out that this plugins implements an option to re-order the list (in case you would like to implement this feature in another plugin).

Sorting addressbooks is out of scope of this ticket.

**Comment by johndoh** [comment]
This might not be appropriate since this issue is assigned to the 1.4.0 milestone but is there a possibility of a wider review of address book config options and their interaction with plugins, e.g. to include issues like #5124?

**Comment by alecpl** [comment]
While it might be handy sometimes to have an option to enable/disable ldap addressbook via `address_book_type` option ignoring `ldap_public`, that would require a BC break. So, let's keep current behavior and fix the documentation.

@johndoh, I'm aware of that, but it's not that simple, so it will have to wait.

**Comment by alecpl** [comment]
Done.
