### ISSUE TITLE
bug: connection error if default domain are ip based and webhost are different from mailhost

### ISSUE THREAD

**Issue by mckaygerhard** [roundcube/roundcubemail#6807]
i setup normal roundcube, lasted stable (also tried 1.4 too)

roundcubemail are in host 10.10.3.40
mailsoftware are in host 10.10.3.30

for configuration made as:

```
$config['db_dsnw'] = 'pgsql://roundcube.pass@localhost/roundcubemail';
$config['default_host'] = 'ssl://10.10.3.30';
$config['default_port'] = 993;
$config['smtp_server'] = 'ssl://10.10.3.30';
$config['smtp_port'] = 465;
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';
```

i'm unnable to connect.. only connect if are in same host as mailsoft...

there's no firewall no iptables rules defined and same net obviously..

domain are valid and dns return correctly :

```
testmxlookup domainmal.net.ve
Domain domainmal.net.ve:
Relay: mx.domainmal.net.ve, Priority: 10, Address: ::ffff:10.10.3.30

nslookup -type=mx domainmal.net.ve
Server:		127.0.0.1
Address:	127.0.0.1#53

domainmal.net.ve	mail exchanger = 10 mx.domainmal.net.ve.
```

error log:

```
[17-Jun-2019 14:31:47 -0400]: <000jnimd> IMAP Error: Login failed for usuario1 from 10.10.3.10. Could not connect to ssl://10.10.3.30:993: Unknown reason in /home/users/roundcube/program/lib/Roundcube/rcube_imap.php on
 line 197 (POST /roundcube/?_task=login?_task=login&_action=login)
```

**Comment by diazvictor** [comment]
I have the same problem.

**Comment by sodomon2** [comment]
Yo Tengo El Mismo Problema

**Comment by sodomon2** [comment]
I Have The Same Problem

**Comment by johndoh** [comment]
Appears to be a config issue rather than a bug. Have a look at https://github.com/roundcube/roundcubemail/wiki/FAQ#problems-connecting-imapsmtp-server-via-ssltls

**Comment by alecpl** [comment]
Most likely SSL validation issue.

**Comment by mckaygerhard** [comment]
seems you @alecpl  and @johndoh  does not read carefully... if i setup locally works.. without TLS or with TLS/SSL  should i open another bug issue?

seems the link by @johndoh help a little to understand: **"imap_conn_options" does not offers a way to specify a different domain rather that the default host!**

**Comment by nerv55** [comment]
roundcube does not permit setup different hostnames  due assumes that same domain for the imap server as for the user login

**Comment by johndoh** [comment]
@mckaygerhard It is very rare to have SSL certs which use an IP address in the CN rather than a domain name and the error: `Could not connect to ssl://10.10.3.30:993: Unknown reason` is most commonly associated with certificate validation failure. You might find more detail about the connection failure in your IMAP server's logs. As a simple test you could use the `imap_conn_options` config to disable certificate verification and see if you can connect. e.g:
```
$config['imap_conn_options'] = array(
  'ssl' => array(
    'verify_peer' => false,
    'verfify_peer_name' => false
  ),
);
```
> if i setup locally works..

You have not provided any information on your alternative setup so its hard to comment but at least in the case of certificate validation different certs and different machines can make a difference so because it works on one does not 100% guarantee it will work on other.

@nerv55 what do you mean exactly? the address of the IMAP server and the user login are only connected in so far as you must have a valid login for the IMAP server.

As @alecpl will probably jump in and say in a minute. This discussion is probably beter suited to the mailinglist or forum as this is a bug tracker not a support platform.

**Comment by mckaygerhard** [comment]
lest resume all: rounducube for gmail! cound no be done just using "gmail.com" as default domain! of course!

i setup with ip based in same machine and works when the domain DNS and ip mail are same... but when domain DNS address are different from the IMAP domain or address could cant reached... 

it's not IMAP problem.. due openwebmai works with both scenarios

**Comment by nerv55** [comment]
@johndoh 
on my case I already have a valid certificate, but the domain of my IMAP server is different from the mail login, also which requires to have the concatenated domain, I was unable to configure this in  roundcube so my work around is install netxcloud and your app-client mail with some modifications. but this is not the best solution.

**Comment by johndoh** [comment]
@nerv55 does `$config['username_domain']` not help?
