### ISSUE TITLE
Enigma: ED25519 Support

### ISSUE THREAD

**Issue by faralsimbor** [roundcube/roundcubemail#6853]
is it possible to implenemt the ED25519 key generation or import?

**Comment by alecpl** [comment]
Openpgp.js supports that so it would be possible. Pull requests welcome.

As for a key import, isn't that working?

**Comment by faralsimbor** [comment]
nope the import fails with the default error

**Comment by alecpl** [comment]
I'll have to test this at some point... Do you have GnuPG >= 2.1 installed on the server? You can enable enigma_debug and check the log to see what's going on.

**Comment by faralsimbor** [comment]
it seems that my ModSecurity config has blocked the key import.

~~~ log snip ~~~
ModSecurity:  [file "/etc/httpd/conf/modsecurity.d/rules/modsecurity_crs-plesk/modsecurity_crs_20_protocol_violations.conf"] [line "219"] [id "960915"] [rev "1"] [msg "Multipart parser detected a possible unmatc
hed boundary."] [severity "CRITICAL"] [ver "OWASP_CRS/2.2.9"] [maturity "8"] [accuracy "8"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/INVALID_REQ"] [tag "CAPEC-272"] Warning. Match of "eq 0" against "MULTIPART_UNMATCHED_BOUNDARY" required. [hostname "webmail.urbach-webhosting.de"] [uri "/"] [unique_id "XTGlDkyGz99hvK@PoNyv
vgAAAAA"], referer: http://webmail.urbach-webhosting.de/?_task=settings&_framed=1&&_action=plugin.enigmakeys&_a=import

**Comment by faralsimbor** [comment]
After i disabled ModSecurity i've got the following enigma log:
[enigma.log](https://github.com/roundcube/roundcubemail/files/3410893/enigma.log)

**Comment by alecpl** [comment]
GnuPG 2.0 does not support ECC and ECDSA keys.

**Comment by faralsimbor** [comment]
Thanks for this info.
So i need to compile GnuPG on my owen, due to leak of .rpm

**Comment by Librechain** [comment]
How is it possible that you **don't possess this knowledge**, Alec? 

I don't mean tot be disrespectful here - but it would be nice if you could at least provide some sort of guidance or helpful information on the moving parts of the code that are specifically responsible for generating the choices that we see in the UI now at default (i.e., RSA 2048 / 4096). 

Can you identify what portion of the code that this is? 

## How Does Enigmail Not Work with ECC / ECDSA? 

We've ruled everything out at this point: 

A) Libcrypt updated (check) 

B) GPG updated (>2.1 as you have iterated many times) - check 

C) OpenPGP.js updated - check 

D) OpenSSL updated... check 

Just asking for at least a **bit more guidance** on what can be done in order to generate these ed25519 through the GUI. Surely you have a few leads (within the code of Enigma itself), that you can point us to right?

**Comment by alecpl** [comment]
Implemented.
