### ISSUE TITLE
Skin Elastic, X-frame-option Nginx

### ISSUE THREAD

**Issue by zden2ksobotka** [roundcube/roundcubemail#6882]
Hello,
I have "Elastic" skin enabled in Roundcube Webmail 1.4-rc1. When I added header 
`add_header X-Frame-Options "SAMEORIGIN";` 
to nginx, i'm getting from console in FF error message "Load denied by X-Frame-Options: https://mail.nic.cz/roundcube/skins/elastic/watermark.html does not permit framing."
When I switch to "classic skin", everything is ok.

Thanks.
Z.

![xframe](https://user-images.githubusercontent.com/48833683/62526205-12d36000-b839-11e9-9956-45d00ffedbd1.png)

**Comment by alecpl** [comment]
I'm unable to reproduce. And that it does not work in elastic only is also strange.

**Comment by alecpl** [comment]
I see you hidden the webmail hostname. Is it different than mail.nic.cz? That would explain why it does not work. Other than that I have no idea, but looks like config issue. No feedback.

**Comment by koxelez** [comment]
Hey, I just stumbled on this problem after enabling SSL and deploying some security-related configs on my server.

It turns out some config was setting "X-Frame-Options DENY" to all requests, server-wide. I went in to change such config to the more permissive yet sane enough value of "SAMEORIGIN".

Lo and behold: Roundcube continued to fail on the "elastic" theme, even though it was getting the correct headers (triple-checked in the network monitor).

I was about to lose my mind over this until it occured to me: "lets test this on a private window".
It worked! It fact it also worked on my phone and even new tabs located in the same window that housed the tab I kept getting errors on.

For the record, roundcube was actually sending "sameorigin" itself (a config default, I gather), but firefox (v76.0.1, to be precise) liked Apache's "DENY" better.

So yeah, it seems firefox ignored the new header value when refreshing that particular tab. For all intents and purposes, it was cursed haha.

I'm dropping this comment here because it was among the top results on google regarding this issue. Might save some people several minutes of unnecessary troubleshooting :ok_hand:
