### ISSUE TITLE
Collected recipients and senders

### ISSUE THREAD

**Issue by alecpl** [roundcube/roundcubemail#6904]
In Roundcube we automatically collect email addresses. Some plugins exist that do this. I
think it would be good to finally move the functionality into core and fix some related
issues. As collecting senders and recipients is related let's consider this together.

1. Collected recipients.

Recipient email addresses (and names) collected (automatically) when sending an email.
We'll make it optional, i.e. when disabled we'll not collect addresses nor
display the addressbook.

I guess we'll have to have an option to use existing addressbook instead of the special
one. So, it would be a single option: "Automatically add outgoing email addresses to":
none/collected recipients/list of writable addressbooks for selection.

I'm not sure we should consider checking an address existence in all writable or all other
addressbooks, but I would like to not add an option for this. Let's check only the above
configured addressbook + all writable addressbooks. Maybe provide a plugin api hook to
modify the list (e.g. Kolab may choose to check all user personal addressbooks).

2. Collected senders.

Email addresses of senders collected when using "Always allow from..." link/button.
This addressbook will be displayed/used only when "Allow remote resources from known
senders" is set.

I guess we'll have to have an option to use existing addressbook instead of the special
one. So, it would be a single option: "Store safe senders in": collected senders/list of
writable addressbooks for selection.

So, when we check if the html message is safe we look for an address in the configured
addressbook.

I'm not sure we should consider only the special addressbook, all writable addressbooks or
all existing, but I would like to not add an option for this. Let's check the configuread
addressbook + all writable addressbooks. And provide a plugin api hook to modify the list.

I'm not sure about the name, maybe it should be "Safe senders"? I'm also not sure about
the wording for these new options above.

3. "My contacts".

We have an option "On request for return receipt send receipt to my contacts...". I think
both above addressbooks should be considered as "my contacts" in this context. I don't
like to add another option. The list could be modified by a plugin if needed.

4. Autocompletion.

I think both above addressbooks should be used for autocompletion. I'm not sure it have to
 be configurable via 'autocomplete_addressbooks' option. Of course, these entries should
have lower prio than entries from other addressbooks.

--

Both these addressbooks will use the same new database table. The table will contain
columns: id, user_id, source_id, email, name.

I think we should allow only a single email address per record. For both sources we'll
allow only entries deletion. No editing. No groups.

References: #5124, #5046, #4971.

ps. this was posted on mailing list but didn't get any feedback. Maybe here it will get more.

**Comment by rmcaninch** [comment]
I like moving it into core. Currently using a plugin for this.

If I’m understanding 2 safe senders correctly as the senders where I am allowing remote images to load; these wouldn’t be contacts that I would want read receipts going to and probably wouldn’t be that useful in autocompletion either. For me, these are typically marketing emails.

If I have a collected recipient, editing it could move to the primary contacts?

**Comment by johndoh** [comment]
> I guess we'll have to have an option to use existing addressbook instead of the special
one. So, it would be a single option: "Automatically add outgoing email addresses to":
none/collected recipients/list of writable addressbooks for selection.

When automatically adding addresses to an existing addressbook may be it would be good to put the new contacts in to specific group or tag them in some way. I'm thinking of the case where a user has enabled the option to collect addresses but then forgotten and then contacts support to complain there are a bunch of entries in their addressbook they didn't add.

**Comment by alecpl** [comment]
@rmcaninch no editing, but you will be able to move such a contact to a normal addressbook and then modify it. On the other hand doing this as a single action might be an UX improvement. We would need a clear warning message in the contact edit form that "editing the collected contact will move it to a selected addressbook".

As for your other use-case. It might make sense, but... if you allowed external images the sender already knows you've red the email (they often use personalized image urls), so why not allowing receipts? Excluding "safe senders" from automatic read receipt replies would mean we don't consider this addressbook "my contacts", which might become confusing.

@johndoh I'd like to do this as simple as possible, i.e. no groups for this case. But we can get back to this idea later if lack of that feature would become a real problem.

**Comment by Disassembler0** [comment]
I'm currently using https://github.com/sblaisot/automatic_addressbook on pretty much all RC instances I have (including two RC 1.4 where it still works nicely) and the [config](https://github.com/sblaisot/automatic_addressbook/blob/master/config/config.inc.php.dist) has pretty sane options IMO, which I would like to see retained even in the core. Namely, you can choose which address book the collected contacts will go in, to which address book they're supposed to move on edit and if they should move at all, and if the collection and autocompletion should happen. All of those you have mentioned.

> I'm not sure we should consider checking an address existence in all writable or all other
addressbooks, but I would like to not add an option for this. Let's check only the above
configured addressbook + all writable addressbooks.

I can imagine cases where there is some shared company-wide address book loaded via CardDAV which is managed just by few people and read-only for all others. In this case, it would be pointless to save the contact again just because the original address book is not writable. Even if the autocollected contacts would have lower priority than the others, I can already see the confusion of users trying to figure why they have duplicates. Especially if they've sent mail to 100s of contacts from the read-only list and then they went to check the autocollected list for "*that guy which I've written to last month and can't remember his e-mail*", which wasn't on the read-only list.

**Comment by alecpl** [comment]
I implemented a big chunk of this, but my time is limited these days, so not everything. Anything extra would need a new ticket or preferably a PR.

I created #7614 for things I like to work on next.

**Comment by marclaporte** [comment]
Related blog post: https://kolabian.wordpress.com/2020/09/26/collected-recipients-and-trusted-senders/
