### ISSUE TITLE
Changing search scope does not reset selected search fields (search_mods)

### ISSUE THREAD

**Issue by rokj** [roundcube/roundcubemail#6919]
Hi,

when I do search in **Current folder** I get results, but when I do search on **All folders** I do not get any result set.

![Screenshot from 2019-09-09 15-24-11](https://user-images.githubusercontent.com/145760/64534636-182f3900-d316-11e9-94ca-16332e06a209.png)
![Screenshot from 2019-09-09 15-24-27](https://user-images.githubusercontent.com/145760/64534619-0d74a400-d316-11e9-8f7a-7b89f4b671ec.png)

**Comment by alecpl** [comment]
What version? What PHP version? Any errors in logs? Did you try with disabled all plugins? Anything in browser console? Maybe it just takes too long and exceeds the request limit.

**Comment by rokj** [comment]
Roundcube 1.3.9, PHP 7.3.6, no errors, I did try disabling all plugins, nothing in browser console, it does not take too long.

**Comment by alecpl** [comment]
Do you see the request in Network tab of the browser console? What is the response?
Enable imap_debug to see what folders are searched and how, and what is the server response.

**Comment by rokj** [comment]
I see request and and response in network tab.

HTTP response from the server is:
```
{ 
   "action":"search",
   "unlock":"loading1568195173895",
   "env":{ 
      "multifolder_listing":true,
      "search_request":"d1963296b1746dd8bc87df614480794f",
      "search_filter":"ALL",
      "messagecount":0,
      "pagecount":0,
      "exists":0
   },
   "texts":{ 
      "spamoz.spamoz":"SpamOZ",
      "spamoz.title":"SpamOZ Settings",
      "spamoz.noconnection":"Cannot contact SpamOZ server. Please try again later.",
      "spamoz.legend_spam":"Spam Settings",
      "spamoz.legend_antivirus":"Antivirus Settings",
      "spamoz.label_level":"Spam Level",
      "spamoz.label_duration":"Spam Duration",
      "spamoz.ndays":"$n",
      "spamoz.label_antivirus":"Enable Antivirus",
      "spamoz.save_success":"SpamOz settings have been successfuly updated.",
      "spamoz.save_error":"An error has occured. Settings were not saved.",
      "spamoz.invalid_data":"Invalid email or spam list name. Please try again.",
      "spamoz.already_exists":"Email already exists in one of the lists.  Please try again.",
      "spamoz.whitelist":"Whitelist",
      "spamoz.blacklist":"Blacklist",
      "spamoz.title_whitelist":"SpamOz Whitelist",
      "spamoz.title_blacklist":"SpamOz Blacklist",
      "spamoz.title_addtospamlist":"Add new email",
      "spamoz.label_email":"Email",
      "spamoz.add":"Add",
      "spamoz.confirm_addtolist":"Are you sure you want to add this email to list?",
      "spamoz.confirm_delete":"Are you sure you want to delete this email from list?",
      "spamoz.alert_notvalidemail":"Please enter valid email address.",
      "spamoz.hint_deletefromlist":"Delete from list",
      "spamoz.ico_title_addtowhitelist":"Add to Whitelist",
      "spamoz.ico_title_addtoblacklist":"Add to Blacklist"
   },
   "exec":"this.display_message(\"Search returned no matches.\",\"notice\",0);\nthis.select_folder(\"\");\nthis.set_rowcount(\"No messages\",null);\nthis.set_pagetitle(\"webmail.arnes.si :: Search result\");\nthis.set_quota({\"used\":633413,\"total\":20971520,\"percent\":3,\"free\":97,\"type\":\"image\",\"folder\":\"INBOX\",\"title\":\"618 MB \\\/ 20 GB (3%)\"});\n"
}
```

**Comment by alecpl** [comment]
So, every folder is asked for
```
UID SEARCH RETURN (ALL) CHARSET UTF-8 OR HEADER SUBJECT {8+}
končala HEADER FROM {8+}
končala
```
and the server responds with an empty result. I don't see a bug here. It looks like it searches in Subject and From headers. Is it not what you selected in the search form?

**Comment by johndoh** [comment]
@alecpl I think I know what they did. Try these steps (in git-master, elastic skin)

1) do a search in "all folders" with only the "subject" selected
2) now do a search in "current folder" with "entire message" selected
3) now change the scope to "all folders" but do not change anything else and click search.

you should see that he search was only run on "subject" if you open the search widget you should see that now only "subject" is selected. It looks like the. It looks like the field selection of your previous search in that scope is being remembered and used when you change scope rather than what is currently selected in the UI.

**Comment by rokj** [comment]
Yeah, something like John described:
https://www.youtube.com/watch?v=hKT4eHnWNgo

**Comment by alecpl** [comment]
This actually is not that easy to fix. I think it was a mistake to make "All folders" search to use separate set of headers/fields (`search_mods`).

I see two options to fix this:
1. Always use current (folder) search fields. Get rid of `search_mods['*']`.
2. Reset fields to current search_mods value when changing the scope (and probably also do not restart the search automatically).

While I understand that it might be useful from performance perspective to not search in entire message or body in all folders, I think from user perspective this is confusing complication. User expects to search in the fields that are currently selected. That's why I'm for the solution 1.

@thomascube what do you think?

**Comment by thomascube** [comment]
@alecpl Using current (folder) search fields is also not transparent for the user. We should probably think of getting rid of the search_mods for each folder and just use one global setting. However, this might be inconvenient when searching in sent or draft folders where we choose other default headers (from/to swapped).

If I understand correctly, the reported issue is more about the search UI not correctly displaying which fields are being used for searching.

**Comment by alecpl** [comment]
@thomascube, Not storing the setting per-folder would be a 3rd option to consider.

Probably storing the fields per-folder is not the main issue. At least it wasn't for a long time. The problem appeared with the multi-folder searches implementation.

When you switch to/from multi-folder, fields selection should be updated. Maybe that would be as simple as that, but... When you are already in a search mode switching to/from multi-folder automatically restarts the search (not in Elastic, but in Larry and Classic). I think this part considering list of fields is confusing (no matter if we update the fields or not). An obvious solution would be to not restart the search automatically. This is what I was talking about in 2nd point of my comment.

On the other hand, maybe all of this is too complicated still and could be simplified somehow? I think the 3rd option might be the best, even if it would bring some small inconveniences.

In Thunderbird, for example, fields are not per-folder.

**Comment by thomascube** [comment]
> An obvious solution would be to not restart the search automatically.

That's certainly a good idea and would likely avoid some of the confusion.

In Elastic the search form is completely reset when switching folders, including the search field is cleared. That I find annoying. In my opinion, the most desirable behavior is to update the UI (search fields) but keep the search term when either switching folders or changing search scope (which finally also changes the folder(s) to be searched in).

**Comment by alecpl** [comment]
>>  An obvious solution would be to not restart the search automatically.

> That's certainly a good idea and would likely avoid some of the confusion.

So, when switching scope we reset fields and do not restart search automatically. That probably could work, but I have a feeling this could be better (simpler?).

> In Elastic the search form is completely reset when switching folders, including the search field is cleared. That I find annoying.

This is the same in all skins. I think it's been simplified at some point, because there was some issues with not resetting the search on folder change. I don't remember whether it was only confusing some users or there was some other issue. That is a separate case, anyway.

**Comment by alecpl** [comment]
According to the documentation "The entry with key '*' stands for all folders which do not have a specific list set.". So, for me it is quite clear that `search_mods[*]` should not be used for "all folders" search, as this wasn't the intention. Considering everything that has been said in this ticket, I think the solution should be:
1. Do not auto-execute search on scope change (Elastic does it this way)
2. Use currently selected criteria instead of the criteria defined in `search_mods[*]`.

**Comment by alecpl** [comment]
Fixed.
