### ISSUE TITLE
"Compose" in Addressbook section don't add all contacts in a group

### ISSUE THREAD

**Issue by gahia** [roundcube/roundcubemail#6972]
There is an issue when you "Compose" a new message choosing a group with more 200+ contacts.

1) Go Addreessbook section
2) Select a group with 200+ contacts
3) Click "Compose"

Only part of the list (~200) is added as recipients. 

* version 1.3.6
* max_recipients has default value then no limit.
* in other cases, all contacts are added as recipients: when Compose from Mail section or when you add manually the group in To, Cc and BCC.

[CSV file with hundreds of dummy emails addresses in a group for testing](https://github.com/roundcube/roundcubemail/files/3740485/emails.with.group.zip)

**Comment by alecpl** [comment]
There's indeed a hard limit in the code set to 200. Most SMTP servers do not accept such a big number of recipients, a time to send so many messages could also exceed our request limit. I.e. it might cause some UI issues. That's probably the reason the limit is there.

I guess we could remove that limitation, and use max_group_members if set, otherwise no limit.

**Comment by alecpl** [comment]
Fixed.
