### ISSUE TITLE
SMTP error following v1.3.10 -> v1.4.0 update 

### ISSUE THREAD

**Issue by mjnewton** [roundcube/roundcubemail#7011]
(Setup: Roundcube v1.4.0 running on the same machine as Postfix v3.3.0)

Yesterday I updated Roundcube from v1.3.10 to v1.4.0 and all went seemingly well apart from one issue - inability to send mail. The error received in the web interface is:

> 'An error occurred. SMTP Error (250): Authentication failed'

I hadn't changed any configuration during/post the update and when I reverted back to v1.3.10 found everything was working again. Checking config/defaults.inc.php for both versions reveals some specific changes:

v1.3.10:

> $config['smtp_port'] = 25;
$config['smtp_user'] = '';
$config['smtp_pass'] = '';

v1.4.0:
> $config['smtp_port'] = 587;
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';

Reverting these settings back to what they were (using config/config.inc.php where I hadn't previously overridden these settings) fixed the issue.

It could well be the case that the changed defaults should've worked on my system, but the main issue for me (and potentially others) is that changing these defaults without warning/notification resulted in a problem that wasn't immediately obvious.

**Comment by alecpl** [comment]
Sorry for that. Maybe we should compare defaults and print a notice when running update.sh.

ps. you probably have to use tls for smtp to make these new defaults working.

**Comment by mjnewton** [comment]
> Sorry for that.

That's okay!

> Maybe we should compare defaults and print a notice when running update.sh.

Yes - that'd work well I think. Even if I didn't fully appreciate the significance of the change I would've known where to look first.

> ps. you probably have to use tls for smtp to make these new defaults working.

Okay, thanks!

**Comment by thomascube** [comment]
FWIW: the changelog in the [release notes](https://github.com/roundcube/roundcubemail/releases/tag/1.4.0) lists this change: "Changed defaults for smtp_user (%u), smtp_pass (%p) and smtp_port (587)"

But I agree that changes to defaults should be listed a separate and more prominent section.

**Comment by mjulian87** [comment]
I am also receiving this error after updating to v1.4.0.

However my issue appears to be related to the localhost variable.

In the previous version I had `$config['smtp_server'] = 'tls://localhost';`. This worked without issue, however after updating, with the same config I receive `'An error occurred. SMTP Error (250): Authentication failed'`.

If I change this to `$config['smtp_server'] = 'tls://mail.mydomain.com';` it works again without issue.

Any ideas?

**Comment by AbelLykens** [comment]
Experienced the same. Had to explicitly set smtp server:

```
$config['smtp_server'] = 'tls://srv33.host.nl';
$config['smtp_port'] = 587;
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';

```

**Comment by alecpl** [comment]
Update.sh script improved.

**Comment by mjnewton** [comment]
Thanks Aleksander. Incidentally I noticed a small typo in line 66 of the revised program/include/rcmail_install.php - it reads 'smt**o**_user' instead of 'smt**p**_user'.

**Comment by FreeBeeEssDee** [comment]
I upgraded my roundcube installation 3 days ago and I'm since struggeling to send mails.
I already had $config['smtp_server'] = 'tls://hostname.domain.tld'; in version 1.3.10 with $config['smtp_port'] = 25;
For 1.4.0 I already added
config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';

I tried these 3 login methods:
$config['smtp_auth_type'] = 'PLAIN';
$config['smtp_auth_type'] = 'LOGIN';
$config['smtp_auth_type'] = '';
 
The server runs FreeBSD 12.0 stable with all ports up to date. In the maillog only very few lines can be found:
Nov 19 23:02:15 hostname postfix/smtpd[39484]: connect from post.domain.tld[10.20.30.40]
Nov 19 23:02:15 hostname postfix/smtpd[39484]: Anonymous TLS connection established from hostname.domain.tld[10.20.30.40]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Nov 19 23:02:15 hostname postfix/smtpd[39484]: disconnect from hostname.domain.tld[10.20.30.40] ehlo=2 starttls=1 quit=1 commands=4

Any ideas whats wrong or what I can try?

Thanks in advance

**Comment by alecpl** [comment]
Checking Roundcube's error log and Roundcube's smtp_debug log usually helps.
