### ISSUE TITLE
Unsaved changes warning not used in Mailvelope mode

### ISSUE THREAD

**Issue by alecpl** [roundcube/roundcubemail#7017]
Steps:
1. Goto mail composer.
2. Click Encrypt button (to switch to Mailvelope mode).
3. Write anything to the mail body textarea (Mailvelope frame).
4. Click on Edit Identities button (or any other task switching button).

Result: Browser opens Settings > Identities interface without warning about unsaved changes.
Expected: A warning is displayed.

So, this is imo a bug. @thomascube you might have more info on `ref.compose_skip_unsavedcheck = true` in Mailvelope mode.

**Comment by thomascube** [comment]
@alecpl I rememebr the problem being that we cannot query the Mailvelope API for the actual contents of the widget and therefore cannot detect whether it has changed since the last saving. You may argue that we can simply request the encrypted message content and compare that but this triggers actions like warnings if a recipient's public key is missing inside the widget. Such warnings are desired and expected when the user hits the "save" button but are likely unexpected and disturbing when triggered by a background task like the unsaved check.

**Comment by alecpl** [comment]
Thanks. Agreed, if we're talking about background tasks. However, for switching task action we should always assume there are unsaved changes and display the warning. That will be better than not showing it and cause the content to be lost.

**Comment by alecpl** [comment]
Fixed.
