### ISSUE TITLE
Text formatting

### ISSUE THREAD

**Issue by giusgenc** [roundcube/roundcubemail#7029]
Hi guys,
for the work I do it is essential to copy/paste the formatting of a text from Microsoft Word or similar to an email on Roundcube. 
This is partly done, such as for bold. But this does not happen for the color of a text or for the size of a text. I hope you can help me.

Thanks

![Immagine](https://user-images.githubusercontent.com/9138763/68762995-a5915100-0617-11ea-9eaa-c7ac6b3d5757.png)

**Comment by alecpl** [comment]
What version? Works for me when pasting from LibreOffice Writer, using Firefox (with some spacing issues) and Chrome (highlight color does not work).

Anyway, this will be a TinyMCE bug. Could you test on the editor on https://www.tiny.cloud/, which uses more recent version of the editor?

**Comment by giusgenc** [comment]
With the Roundcube Webmail version 1.4.0
I tried with firefox and the result does not change.
Copying and pasting text from a word file does not report text size and color.

**Comment by smares** [comment]
We've experienced lots of copy-paste issues from Office to TinyMCE at work and unfortunately, they don't really seem to care, hinting that we should purchase the PowerPaste plugin which is quite expensive. In some cases, formatting is not preserved, sometimes whole paragraphs from Word are missing, sometimes it auto-creates lists when there shouldn't be any or breaks existing lists.

You should test stuff on https://www.tiny.cloud/docs/demo/basic-example/ because the example on the main page has the PowerPaste plugin enabled for example.

**Comment by giusgenc** [comment]
Unfortunately there is no difference, it does not work

**Comment by giusgenc** [comment]
With PowerPaste plugin it works. https://www.tiny.cloud/docs/enterprise/paste-from-word/#powerpastedemo

So should I first paste the text into powerpaste demo and then into roundube or is there a way to paste directly into roundcube?

**Comment by alecpl** [comment]
@smares might be right about bad support for paste in TinyMCE. Unfortunately we can't do much to improve that. We don't really have resources to develop that. On the other hand I would not call this feature essential so not a high prio.

We considered replacing Tiny with something else in the past and there was no good replacement for it. CKEditor was the only option close to Tiny, but from what I see v5 has poor/none paste-from-word support, v4 looks better, but I didn't really investigate if that uses commercial addon or not.

I'm closing this as a wontfix.

**Comment by giusgenc** [comment]
for me it is essential and this means that unfortunately I will not use roundcube.
