### ISSUE TITLE
Roundcube 1.4.1 -> Check DB config -> DB Write:  NOT OK

### ISSUE THREAD

**Issue by teoberi** [roundcube/roundcubemail#7064]
After upgrading to version 1.4.1 in Roundcube Webmail Installer section 3. Test config appears:

> Check DB config
DSN (write): OK
DB Schema: OK
DB Write: NOT OK ([5] database is locked (SQL Query: INSERT INTO "session" ("sess_id", "changed", "ip", "vars")) VALUES ('3019d84a7dbef6280368b031fd4dd5b1', datetime ('now') , '127.0.0.1', 'foo'))))
DB Time: OK

I ran the upgrade from version 1.3.10 to 1.4.0 on two servers without this error. I think something has changed for SQLite with the latest version 1.4.1
I deleted the database and the newly created database has the same problem.
Strange thing, the Test config section loads very hard in version 1.4.1

**Comment by teoberi** [comment]
I can import the contacts from the previously saved .vcf file without errors.
Everything seems to be OK except the message from the previous post.

**Comment by alecpl** [comment]
Confirmed.

**Comment by alecpl** [comment]
I have no idea what's going on, maybe some php/sqlite bug, but I've found that wrapping the INSERT in START/ROLLBACK TRANSACTION fixes the issue. This will the first time we use transactions in Roundcube.

**Comment by alecpl** [comment]
Fixed.

**Comment by teoberi** [comment]
Everything is OK!
The Test config section loads quickly now.

**Comment by Netsplits** [comment]
I'm having an exception at rollbackTransaction() on test.php line 211. After further investigation, startTransaction() returns False. I'm using MSSQL on php 7.3.1 using Microsoft PDO SQL driver, tested on 5.6.1 and 5.7.1-preview. The error code is this:

[0] => 42000
[1] => 3988
[2] => [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]A new transaction is not allowed because there are other threads running in the session.

I just disabled rollbackTransaction() code to finalize setup, but can I have some problems in the future?
