### ISSUE TITLE
Upgrade to 1.4.0

### ISSUE THREAD

**Issue by rokj** [roundcube/roundcubemail#7070]
Hi,

in Post-Upgrade Activities

4. When upgrading from version older than 1.4.0 make sure old files
   in configured temp_dir are removed. Since this version we use constant filename
   prefix and do not remove files not starting with "RCMTEMP".

What does **Since this version we use constant filename prefix and do not remove files not starting with "RCMTEMP".** mean?

Is it safe to remove all files from temp_dir?

**Comment by alecpl** [comment]
temp_dir contains temp files, like mail attachments, thumbnails, etc. You can generally remove all files from there, but be aware there can be also files attached to mail which is composed at the moment by some user.

Normally, Roundcube (session garbage collector) removes the files automatically after some defined time, but because the newest version will remove only these with RCMTEMP prefix, you have to remove files created by older versions by your own.
