### ISSUE TITLE
Doesn't use default_host as smtp_server

### ISSUE THREAD

**Issue by BlackLotus** [roundcube/roundcubemail#7073]
Up until now it was enough to specify 
> $config['default_host'] = "tls://foo.bar.org";
Now I have to manually set
> $config['smtp_server'] = $config['default_host'];
I'm not sure this if this is intended, but since it worked till now without specifying that the smtp host is the same as my default host I'm a bit baffled why the behaviour should change

**Comment by alecpl** [comment]
Some smtp_* options defaults changed in 1.4, but not smtp_server. Smtp_server behavior is the same as before. But in 1.3 smtp_server have been set to 'localhost' by default and empty value is not supported anymore. That should explain it.

**Comment by BlackLotus** [comment]
I know that it changed to using to localhost as default, the question is why? It doesn't really matter for me anymore since I just added the configuration option, but up until now it used the default_host (actually I just guess that it used since I didn't check the code). I can't stand changes in default variables without reason and I don't see the reason in this and I fear that this will break the installations of people without them noticing. Anyway guess this can stay closed then....

**Comment by johndoh** [comment]
Before version 1.3.0 if `smtp_server` was left blank then the PHP `mail()` function was used to send mail. Support for this was removed in version 1.3.0 (commit https://github.com/roundcube/roundcubemail/commit/ee895a2c96a33b854c62a5835a7a1fcd24c02b39). This change was mentioned in the [release notes](https://github.com/roundcube/roundcubemail/releases/tag/1.3.0) at the time. The default was changed because a blank value ceased to have any meaning.

Both before this change and now the correct way to use the same host for IMAP and SMTP server is `$config['smtp_server'] = '%h';` as described in the comments in the config file.
