### ISSUE TITLE
No inline images in mails

### ISSUE THREAD

**Issue by ixess** [roundcube/roundcubemail#7098]
Hi !

I am using IspConfig3 with  RoundCube.

Debian 8
Apache version 2.4.10
PHP version 5.6.40-0+deb8u7

Everything was fine. For some days I noticed, that no no in line images displayed, even when I click 'show images'. 

- Used some older version of RoundCube, around 1.0. Already installed 1.4.1 but still no images. 

- checked some settings I've found in Google
   $config['mime_magic'] = null;
   $config['always_show_images']= true;

- set up debug level 4 but no errors in log.

Have another server, IspConfig as well, other configuration:

Debian 10
Apache 2.4.38
PHP 7.3.11-1~deb10u1

Same problem.

I thought, it's been caused by an OS, or package update, but have a third server with the same config as the first one (fully updated as well):

Debian 8
Apache 2.4.10
PHP 5.6.40-0+deb8u7

That works perfectly.

Any idea ?

Regards

**Comment by alecpl** [comment]
You don't see any images, or you see pink image replacement? Any errors in browser console?

**Comment by ixess** [comment]
Hi, no pink boxes, just a frame around the missing image (pic attached)

Browser error:

Refused to load the font 'https://pages.awscloud.com/rs/112-TZM-766/images/AmazonEmber-Regular.woff2' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

![pic01](https://user-images.githubusercontent.com/58504878/70126368-2a044c00-1679-11ea-9c55-7ba5b08bc7b9.JPG)

**Comment by ixess** [comment]
Error message another mail:

Refused to load the image 'https://www.foxpost.hu/wp-content/uploads/2018/10/csv_edm_banner.jpg' because it violates the following Content Security Policy directive: "img-src 'self' data:".

**Comment by alecpl** [comment]
Roundcube does not set such Content Security Policy. It is your server setup problem.

**Comment by jaro3** [comment]
I have discussed this issue on the dbmail forum recently. It doesn't seem to be an issue of web server setup since with exactly the same web server setup the inline images are shown just fine when using the dovecot imap instead of dbmail imap.  Thought that it was issue of dbmail, but see the recent comment there that this is an issue of roundcubemail:

https://github.com/dbmail/dbmail/issues/519

The images sent as attachment are shown just fine and another mail client such as the Evolution displays the inline images with dbmail imap also just fine.  Interestingly, the inline images which are just URL links to some images on the Internet are also displayed fine !?!?  It is only the inline images encoded within the message body that are not displayed (only empty frames of the correct size shown with the error of Content Security Policy violation if you look at the underlying HTML code) while using the dbmail imap but not dovecot imap.  This issue really drives me crazy...
