### ISSUE TITLE
Roundcube Next Plans

### ISSUE THREAD

**Issue by zainjetha** [roundcube/roundcubemail#7110]
@alecpl @thomascube As the original proprietors of Roundcube 1 and at least one of you an employee of Kolab Systems, kindly provide us an update on Roundcube Next development - and whether there are still plans for it to enter development in the future?

If you don't have an up-to-date indication would you please do the honourable thing and chase @kanarip?

**Comment by zainjetha** [comment]
@gisman @magicfab @mpass3 @mcgeygerhard you all commented on the original ticket, which was closed. Let us do what we can to hold Kolab to account

**Comment by mckaygerhard** [comment]
hi! @gisman @MagicFab @mpass3 @zainjetha o like the idea.. today everyone takes advantage of free software taking advantage of this model of work and development, and the best ends up closed or damaging the community ... long ago gave me the code sources of "myroundcube" and .. by mistake delete the repository because github is now the shit of maycosoft and well I never gave the importance to the issue ... today we need have to give it

**Comment by alecpl** [comment]
We are not employees of Kolab Systems.

**Comment by zainjetha** [comment]
You do a lot of work for Kolab Systems @alecpl and so if not an employee than a very engaged freelancer and I know @thomascube used to do more. 

You both have a moral duty to encourage @kanarip to come forward with a statement given that Roundcube Next arose out of an need from Roundcube 1.

**Comment by thomascube** [comment]
Wrong channel. This is not a Roundcube issue.
