### ISSUE TITLE
Elastic skin: option for no preview

### ISSUE THREAD

**Issue by Gchbg** [roundcube/roundcubemail#7123]
I am greatly missing the option to not have an e-mail preview at all in the Elastic skin. The other two skins support this option. It would be great to have it in Elastic.

**Comment by alecpl** [comment]
Not going to happen.

**Comment by Gchbg** [comment]
Thank you for the detailed reasoning you've given.

**Comment by alecpl** [comment]
The same as with preview pane on bottom feature I do not plan to work on these. That would be burden to support these and we do not have resources to support all kind of features. That's why we decide to not implement some features. Elastic's code is already complicated enough. We'd rather look for simplifications in current feature set.

Use another skin or feel free to create a plugin.

**Comment by Gchbg** [comment]
Thank you for the explanation. I apologize for the sarcasm above.
