### ISSUE TITLE
Clicking on the same folder to reset search should go to page 1

### ISSUE THREAD

**Issue by dboehmer** [roundcube/roundcubemail#7125]
Steps to reproduce:
* search in the current inbox folder for anything
* go to page 2 in message list
* click on the current folder in the folder list

Actual result:
* search is reset
* message list is refreshed
* still page 2 selected

Expected result:
* page 1 is selected

This is similar to https://github.com/roundcube/roundcubemail/issues/3267 but here it's not only about refreshing the folder but resetting the search.

When the search query is reset and a different set of messages (all of them) are displayed keeping the page number makes no sense to me.

I find myself often clicking the folder name because it's a larger and more prominent clickable area than the search reset button.

**Comment by dktcoding** [comment]
Did you mean that the _expected_ result should be:  _(IMHO this should be the expected behaviour)_
- search is reset
- message list is refreshed
- page 1 is selected

Or just page one selected with the search filters in place?

PS: Can confirm that in v1.4.1 [GIT 20191216.1113] the actual result is as described by @dboehmer

**Comment by dboehmer** [comment]
Thank you for clarifying this!

Yes, I meant I expect the behavior to be:
* search is reset
* message list is refreshed
* page 1 (!) is selected

I tested with with the 1.4.1 release.

**Comment by alecpl** [comment]
The page is reset if you select a different folder. Indeed, considering that selecting the same folder resets searching, we should reset the page too. I'm not that sure about the case when there's no searching, but I guess, because we already have the Refresh button, we should reset the page in this case too. This way Refresh action is "state update", and folder selection is "state reset". A clear distinction.

**Comment by alecpl** [comment]
Fixed.
