### ISSUE TITLE
SMTP Error: Authentication failure: SMTP server does not support authentication

### ISSUE THREAD

**Issue by madcreativebg** [roundcube/roundcubemail#7130]
Hello,

I get the error when trying to send mail:

[27-Dec-2019 00:16:41 +0200]: <c7ji2tiv> SMTP Error: Authentication failure: SMTP server does not support authentication (Code: ) in /usr/share/nginx/html/webmail/program/lib/Roundcube/rcube.php on line 1689 (POST /webmail/?_task=mail&_unlock=loading1577398601567&_framed=1&_lang=bg&_action=send)

when using Roundcube 1.4.1. With Roundcube 1.3.10 on the same server and settings there is no problem.

**Comment by alecpl** [comment]
Some config defaults changed in 1.4. See #7011. Because smtp_pass/smtp_user is not set and your server does not allow authentication over insecure channel, you have to either disable authentication (clearing smtp_pass/smtp_user) or add tls:// prefix to smtp_server.

**Comment by johnnyutahh** [comment]
> ... you have to either disable authentication (clearing smtp_pass/smtp_user)...

For me, "clearing" the variables means the following (setting said variables does not seem to work in my Roundcube 1.4.3 rig):

```
$config['smtp_user'] = '';
$config['smtp_pass'] = '';
```

**Comment by trasherdk** [comment]
It could also mean to comment out those 2 lines. Did you try that?

**Comment by johnnyutahh** [comment]
Thanks. I just did. Commenting out the above lines in `/etc/roundcube/config.inc.php` does not work. (The SMTP auth fails when attempting to send an email.)

Setting the variables `= ''` (and empty string) seems to be the only way to do this.

So there seems to be 3 different ways one can interpret "clearing" a variable, depending on the context:

1. set variable to empty string
2. set variable to `null`
3. comment out the variable (although said variable could be defined in another area)

If there's enough confusion in the Roundcube community about this, would it be helpful to clarify things surrounding "clearing a variable"?

**Comment by GwynethLlewelyn** [comment]
Piping in late on a two-year-old closed thread, but since I have also encountered the same error, I'd like just to add my .02 ...

Under PHP 7.4/Roundcube 1.4.3, 'clearing' those variables really means:

```php
$config['smtp_user'] = '';
$config['smtp_pass'] = '';
```

Setting them to `null` will _not_ work.

Under Ubuntu 20.04, Roundcube will be installed with _at least_ a `defaults.inc.php` which gets loaded _before_ `config.inc.php` (as it should be). So, skipping those two settings will not work, since `defaults.inc.php` has the following settings:

```php
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';
```

So these two configuration variables _must_ be explicitly overwritten in `config.inc.php` with the empty string `''`, or else SMTP will refuse to authenticate.

Of course, some Roundcube configurations may be even more convoluted and include several other configuration files beyond these. Actually, I had a few of those around, which I _thought_ weren't being included, but, to be on the safe side, I backed them up and deleted them — just keeping `defaults.inc.php` around, since it's expectable that it will be overwritten with sensible defaults when Roundcube 1.4.4 ships. In other words, if the _only_ configuration file you have is `defaults.inc.php`, do _not_ touch it, but keep it intact, and just override what you wish/need on `config.inc.php`. I believe that _at least_ those two are _guaranteed_ to work, but it's possible that some configurations only ship with  `defaults.inc.php` (and you need to add your own `config.inc.php`) or possible just `config.inc.php`, filled in with _all_ possible configuration values, which you may change — until the next Roundcube version comes around and wipes it clean...

An extra 👍 on the request for documenting this properly! After all, it might just require an extra comment line on `defaults.inc.php`... as @johnnyutahh so well mentioned, there are at least 3 ways to interpret 'clearing', according to context (i.e. each configuration variable _may_ be 'cleared' _differently_...).

**Comment by Goe66els** [comment]
> > ... you have to either disable authentication (clearing smtp_pass/smtp_user)...
> 
> For me, "clearing" the variables means the following (assigning said variables to `null` does not seem to work in my Roundcube 1.4.3 rig):
> 
> ```
> $config['smtp_user'] = '';
> $config['smtp_pass'] = '';
> ```
> 
> (This might be obvious to most Roundcube admins, but I'm a newbie.)

А ларчик просто открывался, 3 дня гугления проб и ошибок... Чувак ты сделал мой день. Спасибо!!!!!


thank you dear friend you made my day !!!

**Comment by trasherdk** [comment]
After a new installation `Roundcube Webmail 1.6.5`, 3 years later, I got bitten by this thing, again :cry: 

```
$config['smtp_user'] = '';
$config['smtp_pass'] = '';
```

Overriding the default fixes that problem.

**Comment by ETNyx** [comment]
Same error, fix suggested in first response works too,...

```php
// default.inc.php
$config['smtp_server'] = 'localhost';
// config.inc.php
$config['smtp_server'] = 'tls://localhost';
```

**Comment by csloz** [comment]
Had same issue in latest, assuming you are using port 587, I needed to keep user/pass and set smtp server tls and port explicitly

$config['smtp_server'] = 'tls://%n:587'; //'localhost';

// SMTP port. Use 25 for cleartext, 465 for Implicit TLS, or 587 for STARTTLS (default)
$config['smtp_port'] = 587;

// SMTP username (if required) if you use %u as the username Roundcube
// will use the current username for login
$config['smtp_user'] = '%u';

// SMTP password (if required) if you use %p as the password Roundcube
// will use the current user's password for login
$config['smtp_pass'] = '%p';





Without that set - these errors:

 SMTP Error: Failed to set sender 'someuser@someserver.com': Authorization required  (without user/pass %u %p ...)
or 
SMTP Error: STARTTLS failed: ready for tls  (without the explicit server type)

**Comment by packetmaverick-dot** [comment]
Just give me the config file setup
