### ISSUE TITLE
Default options for default_port and cipher_method

### ISSUE THREAD

**Issue by cgzones** [roundcube/roundcubemail#7149]
I'd like to suggest strengthening the default options for:

* `default_port`: from imap `143` to imaps `993`
* `cipher_method`: from `DES-EDE3-CBC` to the already suggested `AES-256-CBC`

**Comment by alecpl** [comment]
Default port change would require adding ssl:// prefix to `default_host`. I'm afraid we'll get too many support requests if we do this, also because ssl connection often does not work out of the box (certificate validation). Also, most installations have Roundcube on the same host with imap server so ssl is not required.

For the other option, maybe we could do this, but again that encryption is used for many use-cases, if we change the method it will be a BC break. I don't think it's worth it.
