### ISSUE TITLE
Update 1.4.0 to 1.4.1 failed

### ISSUE THREAD

**Issue by nicrame** [roundcube/roundcubemail#7173]
I've got Database schema update failed. when i try to use /installer/ method.
So i've tried ./bin/update.sh and this is the output:
./update.sh
What version are you upgrading from? Type '?' if you don't know.
?
Executing database schema update.
Updating database schema (2018122300)... [FAILED]
ERROR: Error in DDL upgrade 2018122300: [1060] Duplicate column name 'context'.

I use CentOS 7 (x64) with 5.5.64-MariaDB.
Database use utf8_general_ci.

**Comment by alecpl** [comment]
There were some fixes in 1.4.2 that might be related. Also, in the current database state it looks like you may have wrong version string in `system` table (caused by previous failure), so you might need to verify and apply the db updates manually (don't forget to update `system` table). The list of updates is at https://github.com/roundcube/roundcubemail/tree/release-1.4/SQL/mysql

**Comment by nicrame** [comment]
Thank You. I just done it manually and updated system db too, and now it works fine.
