### ISSUE TITLE
Don't list images attached to multipart/related part as attachments (in HTML mode)

### ISSUE THREAD

**Issue by grape6** [roundcube/roundcubemail#7184]
Mail of content-type multipart/mixed and multipart/alternative has all images of mail body displayed twice, in body itself and second after it. 
Also this images are listed as attachments
RCM git.

![IMG_3155](https://user-images.githubusercontent.com/3339948/72682524-da6dc880-3ade-11ea-8d18-b9c6fa0de81c.JPG)
![IMG_3156](https://user-images.githubusercontent.com/3339948/72682527-dd68b900-3ade-11ea-8478-218ffd56f01c.JPG)

.

**Comment by alecpl** [comment]
Could you provide a message source (with removed message part bodies)? Did you try with disabled all plugins?

**Comment by grape6** [comment]
All the same with only contextmenu enabled. 
I'll provide message later in the evening. Seems, it has nested  body parts.

**Comment by grape6** [comment]
Is this enough?
[msg.zip](https://github.com/roundcube/roundcubemail/files/4099441/msg.zip)

**Comment by alecpl** [comment]
Thunderbird also lists these image attachments. I'm not sure it's because you removed HTML body or because of `Content-Disposition: attachment`. In Roundcube it is definitely caused by the header. These attachments are indeed parts of the multipart/related structure, but I'm not sure this should be enough to skip an attachment.

**Comment by grape6** [comment]
In gmail (both pc & iphone) it's displayed correctly. 
I'll provide msg with HTML body later. 
If you need original one i can send via email.

**Comment by grape6** [comment]
Here is msg with HTML body left.

[msg2.zip](https://github.com/roundcube/roundcubemail/files/4109834/msg2.zip)

**Comment by alecpl** [comment]
Ok, Thunderbird will skip these attachments when using HTML mode. In text mode it will list them on attachments list. So, either it skips them because:
1. they are referred from the body or
2. they are part of multipart/related part (and have Content-ID)
So, I'm not yet sure what we should do. The solution at 2. will be simpler to implement.

**Comment by alecpl** [comment]
Fixed.
