### ISSUE TITLE
Error - Attachment Maximum allowed file size

### ISSUE THREAD

**Issue by fernando-sianet** [roundcube/roundcubemail#7329]
Hello everyone,

Please,  how can i change the value:
Maximum allowed file size
![image](https://user-images.githubusercontent.com/63257457/79368685-2d142080-7f26-11ea-9c01-7a4154acbde0.png)

if I change the file config/defaults.inc.php ===> $config['max_message_size'] = '34M';

appears correctly = 25MB, but changes the alert message for 34MB:

![image](https://user-images.githubusercontent.com/63257457/79369249-07d3e200-7f27-11ea-97b6-c68cbf567173.png)

it seems that the variable changes the two values.

The php.ini:
upload_max_filesize = 100M;
post_max_size = 100M;

**Comment by teoberi** [comment]
Changing the settings in defaults.inc.php is not recommended!
In php.ini configure:
- upload_max_filesize -> Maximum allowed file size is <upload_max_filesize>
- post_max_size -> greater than upload_max_filesize

**Comment by alecpl** [comment]
Configuration issue. Ask on mailing list or forum.

**Comment by elvisef** [comment]
I've had a similar problem today.
It appeared that my VPS postfix configuration had default setting of 10MB per email for attachment.

PHP setting didn't work, because it's already set (post_max_size and upload_max_size).
Same with Roundcube default setting (it's set to 100MB).

So If You're using postfix on Your VPS or dedicated server, I suppose this can help to change the limit: 
[](https://electrictoolbox.com/postfix-email-size-limit/)

Shortly: set "message_size_limit = 20480000" in "main.cf" file (default is: 10240000)
