### ISSUE TITLE
Enhancement: Disable browser password save functionality on login page

### ISSUE THREAD

**Issue by bluikko** [roundcube/roundcubemail#7383]
In some environments it is very important that the end-user does not save the password to browser password manager or auto-complete after the login page is submitted.

I respectfully request a feature that would consist of a flag in the configuration to disable browser password manager/auto-complete for the login page.

A simple `autocomplete=off` apparently would not be a good solution since browsers may ignore it. Workarounds seem to exist.

**Comment by chrestomanci** [comment]
I am aware that some organisations have badly thought out password policies that attempt to force users to memorise passwords, and those polices often result in users re-using them or writing them down. A common example being a requirement to change passwords at frequent intervals. There is now specific advice against doing that without good reason.

https://pages.nist.gov/800-63-3/sp800-63b.html
https://nakedsecurity.sophos.com/2016/08/18/nists-new-password-rules-what-you-need-to-know/

In my view browser based password stores are a useful feature, as they help users create and use unique and more complex passwords than they would use based on human memory alone. They also provide excellent protection against phishing attacks using look-alike domains.

We should not disable such functionality without good reason, and certainly not via workarrounds if the user chooses to configure their browser to ignore the `autocomplete=off` directive.

I think you should spell out your threat model that lead you to the conclusion that browser based password managers should be disabled, as in my view it is more likely that there is a mistake in that threat model and there is no need to restrict the use of password managers.

**Comment by bluikko** [comment]
@chrestomanci I almost wrote down the scenario in the OP but left it out. Should've added it. For example:
- Active Directory is used for mail back-end
- Windows computer has joined the domain, user logs in to Windows with his Active Directory credentials.

In this case the password for both above is the same. Perhaps there is a good password policy, requiring passphrases with a long expiry time or no forced password changes.

The user cannot forget their password - or if they do they couldn't get to Roundcube anyways (cannot login).

If the password is saved to the browser it can be trivially dumped and it could expose a large number of enterprise resources.

**Comment by chrestomanci** [comment]
Your forgot the threat of a look alike phishing domain in your threat model. If your users are forced to type in their passwords from memory every time, then it would be trival for an attacker to collect passwords for your Active Directory accounts by sending a phishing email to your users with clickable links to a fake roundcube email server.

If the new server domain name is something like https://email-your-company.com/roundcube then most users won't notice when they login. If the attackers can proxy your real roundcube server then few will notice even after they login.

On the other hand, if browser password managers are in used, then the browser will notice that the domain is different, not supply a password, and many more users will notice, giving you a chance to stop the phish.

You should think about the relative risks and probabilities of various type of attack. In order to compromise a browser password manager then an attacker would probably need local access to logged in, and not locked windows PC. If they have that level of access then there are other ways to obtain the AD credentials.

**Comment by bluikko** [comment]
I am actually not worried about phishing at all. In my case it is an extremely unlikely scenario, this is an internal enterprise server and not a publicly accessible one. For example it is the default "new tab" page on browsers etc.

The browser password manager is most trivial to dump - either with interaction from user or without. It does not need any special privileges and that's the problem.

**Comment by alecpl** [comment]
Wrote a plugin. I don't think we should use any hacks to achieve this.

**Comment by thomascube** [comment]
Roundcube already has a config option (`login_autocomplete`) which controls the `autocomplete` attribute. We stick to standards and if that's not sufficient, write a plugin to.

**Comment by bluikko** [comment]
@thomascube These days most browsers ignore autocomplete for passwords. I do understand why they do it - for the vast majority of cases it is a good thing.

Understood - thanks for your prompt replies anyways.
