### ISSUE TITLE
unable to initialise database

### ISSUE THREAD

**Issue by sgb999** [roundcube/roundcubemail#7394]
i am unable to update the database for round cube 1.4.4
![roundcube](https://user-images.githubusercontent.com/59648138/82401791-a685be00-9a52-11ea-9499-34122c41c69e.PNG)
![image](https://user-images.githubusercontent.com/59648138/82401805-b30a1680-9a52-11ea-9c16-9059ad32c769.png)

**Comment by trasherdk** [comment]
What does the database log-file say about this?

**Comment by alecpl** [comment]
What version are you updating from?

**Comment by sgb999** [comment]
its a new install so i'm not updating anything
![image](https://user-images.githubusercontent.com/59648138/82431581-b8815400-9a86-11ea-97a3-8495ee27680d.png)

**Comment by alecpl** [comment]
Looks like a problem with sqlite database location. Make sure the path in db_dsnw option is writable.

**Comment by sgb999** [comment]
how do i do that? its just auto generated from step 2
![image](https://user-images.githubusercontent.com/59648138/82434416-b9b48000-9a8a-11ea-9e36-9c8040957850.png)

**Comment by sgb999** [comment]
i just downloaded the older 1.3.* version and that works, there must be a small bug in the newest version that isn't allowing write permissions

**Comment by alecpl** [comment]
There was some changes in how the path is handled, so the bug was it was working before. That db_dsnw is pointing to /var/www/html/mail/roundcubemail file (the path in dsn is relative), and this location is not writeable. You have to use a different path. For security it would be better to use location outside of the Roundcube root.
