### ISSUE TITLE
404 errors, RC 1.4.8

### ISSUE THREAD

**Issue by steffen-nielsen** [roundcube/roundcubemail#7577]
We're experiencing some 404 errors on RC 1.4.8.

The first is found when viewing any email, for instance this email from Microsoft:
`GET https://mydomain.com/?_task=addressbook&_action=photo&_email=msa%40communication.microsoft.com&_error=1 404
`

The second one is when replying to an email:
`DevTools failed to load SourceMap: Could not load content for https://mydomain.com/program/js/tinymce/skins/lightgray/skin.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Comment by johndoh** [comment]
Both of those are normal. The first is because you do not have a photo saved for that contact in your address book and so the place holder image is displayed instead.

The second is caused by DevTools, .map files are typically not included on production systems, they provide information to allow minified code to be re-expanded, they have no purpose in the actual use of the website.

**Comment by Offerel** [comment]
@johndoh is there some way, to not output 404 errors in such a case (skin.min.css.map)? I have seen your PR for the first URL and hope that this will be included in the next release. But i haven't found a solution for the second url. I have this type of url's also on a final release sometimes.
