### ISSUE TITLE
Compose window scrolls to specific position for every key press in message body textbox

### ISSUE THREAD

**Issue by dboehmer** [roundcube/roundcubemail#7622]
While writing longer e-mails the Elastic skin shows this annoying behavior:

Everytime I press a key in the message body textbox the outer compose window scrolls to a specific position. The textbox itself has no scrollbar but the central compose window which includes recipient, etc. and message textbox.

For all lines that can be displayed with the top of the textbox:

![Screenshot_20200922_192343](https://user-images.githubusercontent.com/116007/93916345-b0257800-fd09-11ea-8354-8552df9faac6.png)

For any further lines:

![Screenshot_20200922_192427](https://user-images.githubusercontent.com/116007/93916351-b3206880-fd09-11ea-9238-7df487483b9e.png)

Roundcube 1.4.8
Skin: Elastic

It doesn't happen with the Larry skin.

* Firefox 68.12.0esr (64-bit)
* Chromium Version 83.0.4103.116 (Developer Build) built on Debian 10.4, running on Debian 10.5 (64-bit)

**Comment by alecpl** [comment]
Could you define "for every key press"? For me it scrolls only once when I start typing. Tested with Chrome 85 and Firefox 80.

**Comment by dl1ps** [comment]
I can confirm this Bug. In my opinion this Bug is a show stopper for the Elastic Skin as it makes the Mail Composer pretty unusable. To specify that wrong behavior: The editor does not behave like a normal editor. 

The issue pointed out by the thread starter affects the "plain text" mode of the Mail Composer. Editing a text which is longer than the edit field is very uncomfortable. Whenever a line is edited, that line is moved to the bottom of the editor at the moment when the user has started editing ("pressing keys"). Therefore, I would rate the "plain text" mode of Elastic broken. The jumping is highly distracting and for editing it is essential to be able to read parts of the mail which are above and underneath the line which is currently edited.

This problem does not occur in HTML Mode. But:

HTML mode has another problem:  If a writer has filled the editor with text so that the complete vertical screen area is filled with text, <return> does not raise the text. When starting writing, the editor is showing the line which is currently edited. That behavior is highly distracting and in many cases I would suggest the writer is starting manual scrolling intuitively. 

Summary: in both modes, the Elastic version of the Mail Composer is not behaving as it is expected from a standard editor. I would highly appreciate if this could be fixed soon. Elastic is such a clean and modern skin. It would be a pity if it could not be used productively!

Tested with Chromium and Firefox on Debian 10. Roundcube Version 1.4.8

**Comment by alecpl** [comment]
Fixed.
