### ISSUE TITLE
Schema check fails to detect extra fields

### ISSUE THREAD

**Issue by SpareSimian** [roundcube/roundcubemail#7763]
I tried to log in with a new user and got the error that field "alias" is missing from table "users". I traced this to update 2012080700.sql never getting applied. This seems to be because db_schema_check doesn't check for extra fields that have been removed, only missing ones that have been added in later versions. The array_diff function found there should be done again with the arguments reversed to spot this kind of mismatch.

https://bugzilla.redhat.com/show_bug.cgi?id=1904230

**Comment by johndoh** [comment]
Version 1.1 is not supported any more.

Checking for extra columns is not a reliable solution since plugins or some other third party could have added additional cols. Since version 0.9 Roundcube has used the `roundcube-version` entry in the `system` table to track database schema version and the array diff you refer to is only used as a fallback.
