### ISSUE TITLE
Forwarding email with blocked images attaches blocked.gif

### ISSUE THREAD

**Issue by mas90** [roundcube/roundcubemail#7788]
If I receive a HTML email which references remote images, Roundcube by default replaces them with its own 'blocked.gif' to avoid loading a remote resource -- as expected.  However if I then forward that email, blocked.gif is attached to the forwarded email.  This is unwanted and just leads to confusion by the recipient (especially if the forwarded email contains a real attachment as well).

If I first click 'Allow' to load the original images before forwarding, this does not happen -- the forwarded email refers to the original remote images.

Possible fix: instead of using blocked.gif, Roundcube could rewrite blocked images to a data: URL for an invisible image such as `data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==` (source: https://stackoverflow.com/a/9967193) -- that way the email can be displayed and forwarded without either remote images or blocked.gif.

Alternatively, Roundcube could always forward the email as-is without rewriting image URLs so that the email is not altered when forwarding and so that there is no need to attach blocked.gif.  (But then the mail compose page may unexpectedly load the remote image.)

**Comment by alecpl** [comment]
If you don't want any changes in the forwarded email use "forward as attachment" feature.

Problem with data URIs is that they aren't supported by all mail clients (although I don't have any data to backup this). That's why we replace data URIs in mail content with attachment parts, also for non-forwarded HTML content.

The last alternative suggestion might make sense. I.e. we replace the images with blocked.gif (or data URI) for display purposes and replace it back to the original image location on send/save. However, this could be unexpected by users who see "blocked content", but end up with sending something different.

All in all, I think current behavior is a best compromise.
