### ISSUE TITLE
No oauth login redirect after logout

### ISSUE THREAD

**Issue by downtownallday** [roundcube/roundcubemail#7830]
If 'oauth_login_redirect' is true, the first visit to the login page automatically redirects to the authorization server (good). The user logs in successfully and is redirected back to RCM and presented with their inbox (good). They then log out by pressing the logout button within RCM. The user is subsequently NOT redirected to the authorization server (bad). Instead, they are presented with the standard RCM username/password login page.

My 2 cents

Instead of 'oauth_login_redirect', I would be in favor of a setting to prevent username/password login. It's good to have the RCM landing page ("Welcome to RCM!"), but don't want to allow username/password logins. I would prefer to force users to use 2FA against the authorization server for RCM but still leave PLAIN auth mechanism available on the IMAP server for other MUAs until they can support oauth. The user would be forced to click "Login with {{ oauth_provider_name }}" - there would be no username or password inputs.

**Comment by thomascube** [comment]
> The user is subsequently NOT redirected to the authorization server (bad)

This is intentional. Simply logging out of Roundcube doesn't terminate the SSO session or invalidates the access token. Thus on a subsequuent redirect to the OAuth login, it's very likely that the OAuth service still detects a valid session for the user and immediately redirects back to Roundcube with an authorization code. As a result, the click on "Logout" will just reload Roundcube with a new session. However, I agree that showing the default login form is not perfect either.

I think we have two options here:

* Add an option to hide the default login form (as suggested)
* Propagate the logout action to the OAuth service and invalidate the entire SSO session there.

The latter option might not always be desirable as the user probably doesn't expect to be logged out entirely when leaving Roundcube.

**Comment by downtownallday** [comment]
For option 2, maybe just revoke the token on logout per RFC 7009. Not sure how much support there is for it. Makes sense, though, to keep things clean.

**Comment by thomascube** [comment]
The form fields are now hidden when `oauth_login_redirect` is enabled and the login screen is still shown (on errors or logout).
