### ISSUE TITLE
Invert icons for import & export

### ISSUE THREAD

**Issue by sebastka** [roundcube/roundcubemail#7841]
**Current behaviour** 

On the Contacts page:
- Import is an upward icon
- Export is a downward icon

![](https://roundcube.net/screens/skins/elastic/desktop/screens/editcontact.png)

**Expected behaviour:**
- Import is a downward icon: from user to server
- Export is an upward icon: from server to user

[Google images for import](
https://www.google.com/search?q=import+icon)
[Google images for export](
https://www.google.com/search?q=export+icon)

**Comment by alecpl** [comment]
I don't think this is a big problem since the buttons have labels. Also, we're using this "mapping":
- import == upload (https://fontawesome.com/icons/upload?style=solid)
- export == download (https://fontawesome.com/icons/download?style=solid)

FontAwesome has import/export icons too, but they aren't that clear imo and they have the arrow left/right.

**Comment by sebastka** [comment]
Hi,

I agree the labels do help and that FonteAwesome's icons aren't clear.

Though I believe it is wrong to map import to upload and export to download, it is not a big problem, as you stated. I still hope it will be fixed eventually.

Anyways, thank you for your work!

**Comment by alecpl** [comment]
If we were to switch the icons we'd end up with two identical icons for different buttons near by. I'm talking about the download icon, which is displayed near by the import icon in the mail UI ("More actions" menu). For me it is a wontfix.

**Comment by parazitenew** [comment]
I fixed it in my server. I inverted the two icons, and for the mail UI, I replaced it by "\f56d" (fa-file-download), cause it is about to download the mail as a file. Just a CSS to edit.
