### ISSUE TITLE
Some HTML mails not centered

### ISSUE THREAD

**Issue by jrubenc** [roundcube/roundcubemail#7911]
Hello,

Using 1.4.11

I have a serie of emails, from the same sender that, in Thunderbird (or any other desktop/mobile client), are shown centered but in (desktop version of, at least) Roundcube are shown justified to the left, all of them.

All of them have kind of private information, but I'll attach the less "sensitive" of them, editing just bit the headers. The data part of the email is untouched.

[emailzip.zip](https://github.com/roundcube/roundcubemail/files/6054275/emailzip.zip)

Regards.

**Comment by alecpl** [comment]
So it is something like this:
```
<html>
   <body style="margin: 0 auto; max-width: 560px">
      ...
   </body>
</html>
```
We remove `<html>` element (as we display the html content inline inside our page) and replace `<body>` with a `<div>`. Although we retain `body` styles, it does not work because of `.message-part div.rcmBody, .message-htmlpart div.rcmBody { margin: 0 !important; }` style.

So, it looks like it is intentional. Main reason I think was to prevent attackers to use negative margins to "hide" Roundcube UI elements and replace them with theirs.

**Comment by alecpl** [comment]
The simplest solution to this will be to force `margin-top` only.

**Comment by jrubenc** [comment]
Okay, thanks :)

**Comment by alecpl** [comment]
Fixed.
