### ISSUE TITLE
device_id and device_name are required for private IP

### ISSUE THREAD

**Issue by LugMuad** [roundcube/roundcubemail#7991]
Hello,
I'm totally noob whith github, roundecube, PHP etc so i hope i write in the wright place (my english too is low :) )

I'm trying tu use Roundcube 1.5 (beta) with oauth for googlemail. I use a unpriviligied LXC container in my proxmox, nginx behind a nginx reverse-proxy.

Working as expected with standard login and "unsecure" gmail.

First problem, when i try to connect to google, Roundcube use my local IP : "http://192.168.1.209/index.php/login/oauth" (error 400..) don't know if it's my reverse proxy, proxmox LXC environnement or misconfiguration somewhere ?

Secondly, as i dont understand how the "public function get_redirect_uri()" work i tried to replace the two 
"'redirect_uri'  => $this->get_redirect_uri(),"
 with 
"'redirect_uri'  => 'https://MYDOMAIN//index.php/login/oauth',"
And, oh magic, it seem to work.
Sadly when i finish the google authorization procedure i'm back at default login page, but badly formatted :(
I imagine that the server still using my local IP somewhere, but i'm lost a this point.

Any help is welcome.

**Comment by LugMuad** [comment]
For information, if it can help someone, was missing "proxy_set_header Host $host;" in my NGINX reverse proxy, but now i get the same error with "http://my.domain/index.php/login/oauth". In my noobiness i didn't find how to make RoundCube to expose https for now.

**Comment by thomascube** [comment]
The hostname part of the URL is composed in [rcube_utils::resolve_url()](https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube_utils.php#L1355) where PHP's `HTTP_HOST` env variable is used. The https protocol is detected in function [rcube_utils::https_check()](https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube_utils.php#L656) which looks at either the `HTTPS` env variable or the `X-Forwarded-Proto` header added by the reverse proxy. The latter also depends on the `proxy_whitelist` Roundcube config option which needs to list the IP of the nginx reverse proxy for security reasons.

> i'm back at default login page, but badly formatted

If you end up here, Roundcube probably failed to fetch the access token from the OAuth service or the IMAP login with the obtained credential fails. Both incidents should be visible in Roundcube's error log. The issue wit the badly formatted login page is fixed in git master so consider to use a snapshot from Git instead of the 1.5-beta release.
