### ISSUE TITLE
Replace weakness default password_minimum_score  

### ISSUE THREAD

**Issue by AlgoSolu** [roundcube/roundcubemail#8003]
Hi,

Currently, the default password_minimum_score in the /plugins/password/config.inc.php.dist is set to 0. 

0 is the weakness and 5 is the strongest. 
Maybe 3 should be better than 0... 

Regards

**Comment by alecpl** [comment]
The weakest value is `1`. With `0` the password strength checking is disabled. If I remember correctly the password strength checking options were always disabled by default. Also the minimum length option is 0.

Maybe we should use different defaults. However, I could also understand someone setting `password_minimum_length=16` and do not bother with other strength checks.

Also it needs to be noted that using score=3 with no `password_strength_driver` will have the same effect as 2 or 5, because the default checks evaluate to 1 or 5 only. And it will require a number or non-alphanumeric character in the password which some users don't like.

That being said, I would probably not touch the default score, but we can set the minimum length to 8.

**Comment by AlgoSolu** [comment]
It could be a good start by setting the default minimum length to 8. 
thanks

**Comment by alecpl** [comment]
Done.
