### ISSUE TITLE
Inserting a group from non-default source fails in the Insert contact(s) dialog

### ISSUE THREAD

**Issue by iganchev85** [roundcube/roundcubemail#8095]
Hi guys.
I have problem with my roundcube.
I installed addressbook pluging and everything looks great, but when i use the search engine to find some contact, if is single contact no issue, but if I try to add group to recipient, just add empty space and comma " ,".
If try to add group without search engine - no problem, works great. The problem appears only if use search engine.
I tried different versions of roundcube with no other plugins and different versions ot globaladdressbook - everytime same result.

If the group is in my private contact list - no issues.

**Comment by johndoh** [comment]
@alecpl this is a bug in the core. its because the search does not return source information.

steps to recreate:
1) on the compose screen open the Add Contacts dialog
2) search for a group name in a non-default address book
3) double click the group
4) the executed request has the correct group id but uses the default address book as the source

by contrast:
1) on the compose screen open the Add Contacts dialog
2) select the addressbook which contains the group you are looking for
3) search for that group name
3) double click the group
4) the executed request has the correct source id and group id and the recipients are inserted

confirmed in 1.4 and git-master

**Comment by alecpl** [comment]
Confirmed. Works with autocomplete, but not with the Insert contacts(s) dialog.

**Comment by alecpl** [comment]
Fixed.
