### ISSUE TITLE
Display inline images even if they have incorrect content-type

### ISSUE THREAD

**Issue by syncgw** [roundcube/roundcubemail#8158]
Hi attached MIME is shown as:

![grafik](https://user-images.githubusercontent.com/2334583/128232532-9b6dee0a-0819-4f24-bea2-fc9fe18050dc.png)

"27 Keule.gif" should be shown inline and NOT as an attachment.
[MIME03.txt](https://github.com/roundcube/roundcubemail/files/6933515/MIME03.txt)

**Comment by syncgw** [comment]
Forgot to mention: RoundCube 1.4.11, no plugins activated.

**Comment by alecpl** [comment]
The problem is with the attachment Content-Type. The http response to the image request is "This attachment is suspicious because its type doesn't match the type declared in the message. If you do not trust the sender, you shouldn't open it in the browser because it may contain malicious contents. Expected: text/calendar (.gif); found: image/gif (.gif)".

While it's an obvious mistake in the message, I guess we could be smarter here.

**Comment by syncgw** [comment]
Thank you so much for clarification! I will contact developer of mail creation program if they can take more care when creating inline graphics.

**Comment by alecpl** [comment]
Fixed.
