### ISSUE TITLE
No "none" option in "Store outgoing email recipients in..." and "Store trusted senders in..."

### ISSUE THREAD

**Issue by darren12345** [roundcube/roundcubemail#8368]
RC 1.5.1, Debian Bullseye

These options have defaulted themselves to "Collected Recipients" and "Trusted Senders" respectively, noticed due to the creation of two new address books that weren't there before. I'm quite sure I must have had these options turned off before, but now there is only an option to save them in a particular addressbook, and there is no "Do not save" type option.

**Comment by alecpl** [comment]
The "collected recipients" selector has "---" option.

The "trusted senders" has no "none" option because the behavior is controlled via Preferences > Displaying Messages > Allow remote resources (images, styles) option. So, all you can do here is to say which addressbook to use for this purpose.

These options are new in 1.5.
