### ISSUE TITLE
PHP Fatal error: Uncaught Error: Class 'GuzzleHttp\Client' not found

### ISSUE THREAD

**Issue by VoiletDragon** [roundcube/roundcubemail#8424]
Hi,

I upgrade to Roundcube 1.5.1 but i am see in my mail logs a problem with GuzzleHttp\Client' not found in /opt/www/roundcubemail-1.4.7/program/lib/Roundcube/rcube.php:27, Although Roundcube is working perfectly fine i am seeing these errors. Any ideas?

PHP Fatal error:  Uncaught Error: Class 'GuzzleHttp\Client' not found in /opt/www/roundcubemail-1.4.7/program/lib/Roundcube/rcube.php:271

Thanks.

Jack.

**Comment by VoiletDragon** [comment]
Update, 

I just checked line 271 and the following is there. I believe that this could be a bug ?

`/**
     * Initialize HTTP client
     *
     * @param array $options Configuration options
     *
     * @return \GuzzleHttp\Client HTTP client
     */
    public function get_http_client($options = [])
    {
        return new \GuzzleHttp\Client($options + $this->config->get('http_client'));
    }
`

**Comment by alecpl** [comment]
I don't know what kind of a release package you used, but you miss a required dependency. Run `composer update`.

**Comment by VoiletDragon** [comment]
Hi,

Thanks for you reply, I downloaded the Complete package from Github then i ran the following, sudo bin/installto.sh after extracting. The composer update where do i do this sorry ? never had to do that before.

Thanks.

Jack.

**Comment by revoltown** [comment]
? the same issue...

**Comment by jasonmacer** [comment]
Good afternoon all.

I just downloaded the master package to upgrade my 1.4.2 roundcube version to 1.6.6, and I am running into this issues even though I am seeing that [rcube.php](https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube.php) was updated back on February 16th with commit [#9358](https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube.php). 

I was following the [UPGRADING ](https://github.com/roundcube/roundcubemail/blob/master/UPGRADING)instructions after downloading and unpacking master.zip. The command run was "[user@host roundcubemail-1.6.6]# ./bin/installto.sh /usr/share/roundcube/"

What follows is the error log entry:

`[14-Mar-2024 12:25:26 America/Chicago] PHP Fatal error:  Uncaught Error: Class "GuzzleHttp\Client" not found in /root/roundcubemail-1.6.6/program/lib/Roundcube/rcube.php:271
Stack trace:
#0 /root/roundcubemail-1.6.6/program/include/rcmail_oauth.php(205): rcube->get_http_client(Array)
#1 /root/roundcubemail-1.6.6/program/include/rcmail_oauth.php(104): rcmail_oauth->__construct(Array)
#2 /root/roundcubemail-1.6.6/program/include/rcmail.php(157): rcmail_oauth::get_instance()
#3 /root/roundcubemail-1.6.6/program/include/rcmail.php(95): rcmail->startup()
#4 /root/roundcubemail-1.6.6/program/include/clisetup.php(30): rcmail::get_instance()
#5 /root/roundcubemail-1.6.6/bin/installto.sh(24): require_once('/root/roundcube...')
#6 {main}
  thrown in /root/roundcubemail-1.6.6/program/lib/Roundcube/rcube.php on line 271
`

The server is running PHP 8.1.27 on CentOS 7.9.2009. I'm actually upgrading because I'm hopeful that this version will have fixed the integration with ISPConfig 3. That's the hope at least.

I am going to go down a version and try again, but if anyone has any suggestions, I am all ears.

**Comment by jasonmacer** [comment]
As a brief update. I was able to clone the 1.5 branch and the installer ran and upgraded my 1.4.2 to 1.5-git.

Granted, the password is still not updating is not. I still keep getting "Cannot save new password." So, now to go dig into that.

**Comment by yafet-dev** [comment]
facing same dependancy issue, I installed roundcube using ispconfig

**Comment by yafet-dev** [comment]
![image](https://github.com/user-attachments/assets/f6d02fd4-ae0d-4964-8214-b13a12cfc971)

**Comment by dmknght** [comment]
I'm using docker image `php:8.2-apache`. My best quest is to install `php-guzzlehttp-guzzle` however i have error `E: Package 'php-guzzlehttp-guzzle' has no installation candidate`. Docker image is using debian bookworm repo. The other solution is to install `composer` via apt then run `composer update`. However this oslution gives me broken dependencies error.
