### ISSUE TITLE
Reply from received To address

### ISSUE THREAD

**Issue by infogulch** [roundcube/roundcubemail#8452]
I have a mail server that delivers emails sent to `username+anything@example.com` to `username@example.com`, gmail-style. I like this feature because it provides me with more detail about where a sender discovered my address because everywhere that I give my email gets a unique `+suffix`.

However, when I try to reply to one of these emails, it always responds from the base email address with no suffix. This can confuse recipients, and especially impacts customer support email systems. My current workaround is to add a new "Identity" and selecting it manually whenever I'm responding to one of these emails, but that is becoming quite tedious due to many senders that I've provided with unique addresses, and is prone to misclicks and me overlooking it.

Here are a few reasonable changes that I think would help make this smoother and less error-prone:
* Showing a notice that the email of the chosen identity that you're responding with does not match the email in the To field on the email you're responding to.
* Make it easier to create a new identity that matches the To field. (Either automatically, or with a single button press.)
* Choose an existing identity that matches the To field by default.

Thoughts?

**Comment by manfredu** [comment]
The general rule is that identities are matched by the to-address you are replying to. So if a+b@c exists, this identity would be choosen. This already works. In case it does not exist my suggestions would be that if only a@c exists as identity this would be choosen, but the sender email would be set to the complete a+b@c address. This would avoid the need to create numerous identical identities, but still the specific sender address, which identifies the recepient and his replies. 
The only issue remains with the initial email to the recipient. I guess in your case this is not sent from roundcube, since then the identity would already exist. One would need an option to specify the +b part in addition to selectiong the idenity...

**Comment by alecpl** [comment]
Maybe https://github.com/r3c/custom_from is your solution.
