### ISSUE TITLE
rc "forgets" there's an archive folder

### ISSUE THREAD

**Issue by reven** [roundcube/roundcubemail#8512]
Mail server works well and Archive folder is set up properly (no issues from desktop clients). Upon logging in to rc the Archive folder is properly set up and the message view includes the "Archive" button; also the folder icon on the pane is the expected. After coming back to the tab and refreshing, the Archive folder has a normal folder icon and the "Archive" button in the message pane disappears.

Refreshing the page doesn't help. However logging out and back in again restores the expected behavior.

I don't know if there is a time-out issue; I haven't been able to pinpoint it. Below are my active plugins in case this depends on any of them. I'd be glad to provide any more info if someone wants to help me troubleshoot.

```
$config['plugins'] = [
        'acl',
        'additional_message_headers',
        'archive',
        'attachment_reminder',
        'autologon',
        'emoticons',
        'enigma',
        'example_addressbook',
        'filesystem_attachments',
        'help',
        'hide_blockquote',
        'http_authentication',
        'identicon',
        'identity_select',
        'jqueryui',
        'managesieve',
        'markasjunk',
        'new_user_dialog',
        'new_user_identity',
        'newmail_notifier',
        'password',
        'persistent_login',
        'reconnect',
        'show_additional_headers',
        'squirrelmail_usercopy',
        'subscriptions_option',
        'userinfo',
        'vcard_attachments',
        'virtuser_query',
        'zipdownload',
        'rcguard',
        'sauserprefs',
        'carddav',
];
```

**Comment by alecpl** [comment]
> After coming back to the tab and refreshing

You mean it needs time? Does an immediate page refresh reveal the same issue? What version? Try with all plugins, except archive, disabled, especially the external ones.

**Comment by reven** [comment]
This is Roundcube Webmail 1.5.2. No, after login, an immediate reload of the page does not cause the issue. It's really hard to replicate this behavior in terms of after how much time logged in it will happen, but it's consistent in terms that eventually it always happens.

I will try disabling plugins and see if I can pinpoint any changes.

**Comment by Eckankar** [comment]
I have been experiencing what I believe to be the same issue.

I am not hosting my own RC, but running on MXRoute.com's setup.

The version of RoundCube is also 1.5.2, and the plugins listed in the About page are:

---

advanced_search	3.4
archive	3.5
filesystem_attachments	1.0
jqueryui	1.12.0
managesieve	9.4
password	5.3
persistent_login	1.0.2
zipdownload	3.4

---

Much like the original reporter, I cannot give an exact time for how long it takes for it to occur, but after "a while" (on the order of maybe a day to a couple of days), when I open my RC browser tab it will not show the archive button.

If I'm in this state and I visit Preferences > Special Folders in the settings, the correct archive folder will be listed. If I then return from the settings page to the mail overview (even without clicking "Save"), the archive button on the mail messages will be back.

Unfortunately I'm not able to do much experimentation on the setup on my end due to it being externally hosted, but I can indeed confirm the issue.

**Comment by alecpl** [comment]
I suspect persistent_login plugin. It keeps you logged in, but maybe does not keep the session/state properly.

**Comment by reven** [comment]
After some testing it does seem that persistent_login is the culprit for this issue. I haven't been able to replicate the issue with persistent_login disabled. I'll close this issue and raise the issue in the the plugins github. Thanks for the help.
