### ISSUE TITLE
SMTP auth failed with STARTTLS but receive an code 220

### ISSUE THREAD

**Issue by earendilfr** [roundcube/roundcubemail#8780]
Hello,

I have an issue with my configuration of roundcube and my postfix server.
Everything working fine when I use the SMTP server directly from a client (like Thunderbird).

But if I try to send an email with roundcude, I receive an error: 

And the following logs:
```
Nov 11 16:05:09 server roundcube[2622854]: <nhaf0b9a> Send new auth cookie for xxxxxxxxxxxxxxxxxx
Nov 11 16:05:09 server postfix/submission/smtpd[2622626]: connect from localhost[::1]
Nov 11 16:05:09 server roundcube[2622854]: <nhaf0b9a> PHP Error: STARTTLS failed (POST /?_task=mail&_unlock=xxx&_framed=1&_action=send)
Nov 11 16:05:09 server postfix/submission/smtpd[2622626]: lost connection after STARTTLS from localhost[::1]
Nov 11 16:05:09 server roundcube[2622854]: <nhaf0b9a> PHP Error: Invalid response code received from server (POST /?_task=mail&_unlock=xxx&_framed=1&_action=send)
Nov 11 16:05:09 server postfix/submission/smtpd[2622626]: disconnect from localhost[::1] ehlo=1 starttls=1 commands=2
Nov 11 16:05:09 server roundcube[2622854]: <nhaf0b9a> SMTP Error: STARTTLS failed: 2.0.0 Ready to start TLS (Code: 220) in /srv/www/html/roundcube/program/lib/Roundcube/rcube.php on line 1795 (POST /?_task=mail&_unlock=xxx&_framed=1&_action=send
```

But, if I read correctly the documentation, the configuration indicate that we should perform a STARTTLS connection...
```php
// ----------------------------------
// SMTP
// ----------------------------------
// SMTP server host (for sending mails).
// Enter hostname with prefix tls:// to use STARTTLS, or use
// prefix ssl:// to use the deprecated SSL over SMTP (aka SMTPS)
// Supported replacement variables:
// %h - user's IMAP hostname
// %n - hostname ($_SERVER['SERVER_NAME'])
// %t - hostname without the first part
// %d - domain (http hostname $_SERVER['HTTP_HOST'] without the first part)
// %z - IMAP domain (IMAP hostname without the first part)
// For example %n = mail.domain.tld, %t = domain.tld
$config['smtp_server'] = 'tls://localhost:587';

// SMTP port (default is 25; use 587 for STARTTLS or 465 for the
// deprecated SSL over SMTP (aka SMTPS))
//$config['smtp_port'] = 587;
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';
```

And when I do the `ncat` command directly the IP:PORT, I can see the STARTLS directive sent by the server:
```
server% ncat localhost 587
220 server ESMTP
EHLO toto
250-server
250-PIPELINING
250-SIZE 52428800
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250-SMTPUTF8
250 CHUNKING
QUIT
221 2.0.0 Bye
```

Did you have think it's a bug or a missconfiguration on my side?

**Comment by earendilfr** [comment]
OK: found. It's better to reach the SMTP server with the real hostname and not localhost...

**Comment by barreljan** [comment]
@earendilfr Thanks a lot for this comment! Was already submitting myself to the loony bin after a few hours

**Comment by jdelker** [comment]
Some more background for those who stumble about this too:

Unfortunately, the error shown in the log does not reveal the true error cause.
The hostname used for the `smtp_host` must match the certificate returned from the server on activating the STARTTLS.
If you see that `STARTTLS` failed` error, it most probably does not.

There are two options to solve it:
1. Adjust the `smtp_host` accordingly as suggested by @earendilfr previously, or
2. Disable the certificate verification by setting the `smtp_conn_options` `(see` `defaults.inc.php` for details).

Please note: In general, disabling certificate validation is something I would never recommend, because it is almost always a bad idea.
In my case, I'm running roundcube in a container and must connect to the SMTP server on `host.containers.internal`, which of course doesn't match the server's real hostname (and certificate).
