### ISSUE TITLE
Support multi-email-address setup

### ISSUE THREAD

**Issue by stoecker** [roundcube/roundcubemail#8799]
Hi,

for some years I now use a whole (sub-)domain for e-mail, where the user part of the email address is individual for each use case. That's extremely helpful for detecting inappropriate mails, as they usually have the wrong user part.

E.g.
ebay@domain.tld for ebay and amazon@domain.tld for Amazon and so on.

The alpine mailer had an option to handle such emails which essentially consisted of 2 parts:
* The From field of a sent email could be edited
* The From field of a sent email was auto-filled with the To address of the answered mail when it filled the criteria (e.g. was of the form *@domain.tld)

Please also support that system also in roundcube. It's extremely helpful. The current way to add a new identity is a rather crude workaround.

**Comment by alecpl** [comment]
Try this https://github.com/r3c/custom_from

**Comment by stoecker** [comment]
Thanks. That seems to do exactly what I need.

**Comment by MiMoHo** [comment]
Instead of setting up multiple identities, it is favorable to have the [custom_from](https://github.com/r3c/custom_from) plugin. But when a web hosting company sets this up for all customers, some wish to always reply from the default identity while others prefer the approach as suggested by @stoecker and various others like https://github.com/roundcube/roundcubemail/issues/8556, https://github.com/roundcube/roundcubemail/issues/8452, https://github.com/roundcube/roundcubemail/issues/3272 which is not yet supported by the plugin in the frontend.
Before upgrading the plugin, I would like to introduce its basic functionality to Roundcube natively allowing to edit the local-part of email addresses in Roundcube for all supported domains in combination with https://github.com/roundcube/roundcubemail/issues/9482 in case the web hosting company refuses to install a plugin that allows for a complete virtual alias. This would also require a reply setting in the preferences as a drop-down option to either reply using the default identity or "to" address by default. With an enhanced custom_from plugin, even more variations could be offered: https://github.com/roundcube/roundcubemail/issues/9343#issuecomment-2151070719
Is this something you @alecpl would be interested to implement to better address the needs of users that rely on the default Roundcube installation from web hosting companies while preserving and even enhancing spam protection by allowing users to reply to individual email addresses without maintaining identities? Abused email addresses could be easily blocked by filter so the user won't receive spam mails.
I'd be open to financially incentivize development if required for such useful improvements.
