### ISSUE TITLE
Unsupported PHP version. Required PHP >= 7.3.

### ISSUE THREAD

**Issue by webbymaster** [roundcube/roundcubemail#8830]
After updating, I get the error "Unsupported PHP version. Requires PHP >= 7.3." ((( Tell me how to solve?

**Comment by Starcr0ss** [comment]
You just have to upgrade your website for webmail so that it runs on a newer version of PHP. This error tells me that you're running on an old PHP version that is very EOL. I'd strongly recommend PHP 8.1 because it is pretty new and 8.2 likely isn't well-supported by devs yet.
I don't know how you specifically would do it on your server, but on my server I use Hestia CP and upgrade my server PHP version by using a dropdown menu.
