### ISSUE TITLE
$config['http_client'] should have a default timeout set

### ISSUE THREAD

**Issue by cPAusaf** [roundcube/roundcubemail#8865]
Currently there is no timeout defined for $config['http_client']. If a resource in an email (say a favicon from United.com) does not load, Roundcube will lock its SQLite database and essentially make Roundcube unusable for that user:

```
[17-Jan-2023 00:58:02 -0500]: DB Error: [5] database is locked
[17-Jan-2023 00:58:27 -0500]: DB Error: [5] database is locked
[17-Jan-2023 00:58:27 -0500]: DB Error: [5] database is locked
```

Having a default timeout set (ie - 15/30s) will at least ensure that Roundcube can still be used if a resource was unable to be loaded within that time.

**Comment by alecpl** [comment]
Another reason to not use SQLite for anything other than tests.

Anyway, we should maybe add some sane default for timeout in `rcube::get_http_client()`.

**Comment by LauraTaylorUK** [comment]
Hey thats not fair, I'm using SQLite in 10+ roundcube servers with great success. On average each server has about 60 to 100 email accounts.

PS:
I've set http_client to 3 seconds without any problems. I expect anything that takes longer than 3 seconds to be a broken resource.

**Comment by MikeDVB** [comment]
> Hey thats not fair, I'm using SQLite in 10+ roundcube servers with great success. On average each server has about 60 to 100 email accounts.
> 
> PS: I've set http_client to 3 seconds without any problems. I expect anything that takes longer than 3 seconds to be a broken resource.

We're using RoundCube, via cPanel, on dozens of servers hosting tens of thousands of inboxes and generally it works fine.

I am the one that reported this issue to cPanel and then cPanel opened this report with RoundCube.  cPanel _could_ just set a timeout but they seem to prefer passing the buck to RoundCube.  cPanel _does_ manage the configuration file because any custom settings in the RoundCube configuration file get lost when cPanel updates RoundCube.  In essence they manage the config but won't set sane defaults and expect the vendor to do it.

The reason we found the issue was one end user out of tens of thousands reporting that RoundCube kept dying on the.  Dying to the point that they could not log into Webmail at all.

Upon investigation it was discovered that RoundCube was connecting to an Akamai IP once per second over and over with no end trying to retrieve a resource.

That resource was a favicon for an email from United [the airline].

It seems that United's CDN, Akamai, does not like the UserAgent that Guzzle sends [RoundCube's HTTP Client] and doesn't reject the connection but simply never responds.

Since RoundCube has the SQLite database open while waiting on this resource, the resource never loads, the database gets locked indefinitely.

Going a bit further - it seems this is also related to an issue reported to Guzzle that was never addressed and went stale at https://github.com/guzzle/guzzle/issues/2783 [ Default for read_timeout option is not set ]

According to this case, a worker could hang for days, as it doesn't use the other timeouts in PHP because it isn't set to anything in the code currently.  That was our experience.

Admittedly this is exceptionally rare.  Having been using cPanel + RoundCube since 2007 I've only seen it three times and all three times were the same client / user in the same mailbox.

That isn't to say sane defaults should not be set - either by RoundCube distributing the software to cPanel or cPanel distributing it to their end users.

My worry about this is that RoundCube will say 'You should just change the defaults if you don't like them,' and then cPanel will say, 'It's a RoundCube issue and they are the ones that should set defaults.'  Basically meaning neither organization solves the problem and the only people that suffer are the end-users.

If there is a _good_ reason not to set timeout defaults - I'm all ears - otherwise, why not just set a sane default?

I mean even if you set it to something like 60 seconds - that would _at least stop a multi-day hang where a user cannot access their email._

Now don't get me wrong - cPanel could absolutely move away from SQLite for RoundCube.  There are a myriad of other options.  That would avoid RoundCube going unavailable and webmail dying for the user but would not prevent the RoundCube PHP process trying and failing repeatedly to retrieve a resource it cannot get forever until killed and that's the real problem, imho.

cPanel using SQLite and this hung process causing that SQLite database to be locked is a symptom of the issue and not a cause.  Without that symptom the issue would still exist.

**Comment by LauraTaylorUK** [comment]
@MikeDVB 
I understand why cPanel does not want to address the issue. It is typical open source etiquette, to pass the issue to the up-stream project. In addition, everyone using Roundcube will benefit from the fix, including down-stream projects.

btw `read_timeout` should default to the php.ini value of `default_socket_timeout`, which has a default value of 60 seconds.

**Comment by MikeDVB** [comment]
> @MikeDVB I understand why cPanel does not want to address the issue. It is typical open source etiquette, to pass the issue to the up-stream project. In addition, everyone using Roundcube will benefit from the fix, including down-stream projects.
> 
> btw `read_timeout` should default to the php.ini value of `default_socket_timeout`, which has a default value of 60 seconds.

I didn't look into it deeply.  Mostly just passed on what cPanel told me in regards to that other timeout.

I do understand passing it up the chain to improve RoundCube for _everyone_, don't get me wrong.  That said cPanel cannot act as though they just bundle the software in with zero modification or customization at all.  They have to do _some_ configuration to make it work as it does in the cPanel environment.  Setting a couple of default settings isn't a bridge too far IMHO.

That said - doing both - passing it up the chain _and_ setting the defaults on the version they distribute wouldn't be a bad thing I do not think.

**Comment by alecpl** [comment]
Guzzle HTTP client has three timeout options (https://docs.guzzlephp.org/en/stable/request-options.html):
- `timeout` (default: 0 - no timeout)
- `read_timeout` (default: `default_socket_timeout`)
- `connect_timeout` (default: 0 - no timeout)

So, I suggest we set `['timeout' => 30, 'connect_timeout' => 5, 'read_timeout' => 120]`.

**Comment by alecpl** [comment]
Done.
