### ISSUE TITLE
image attachments no longer displayed in 1.6 due to #7184

### ISSUE THREAD

**Issue by hthpr** [roundcube/roundcubemail#8870]
I upgraded from 1.5.3 to 1.6 and I received a report that attached images from Verizon (vzwpix.com) are no longer displayed in RC.

I narrowed it down to issue #7184. If I comment line 209-211 for program/actions/mail/show.php in that commit the attachment can be viewed again. Attached are a couple screenshots of what the message display looks like with the 1.6 release and then the code commented.

I also included with some privacy the original message headers and start of attachment content. I have removed the data of the attachment. 
[msg.txt](https://github.com/roundcube/roundcubemail/files/10460583/msg.txt)
I'm sure it's an issue with the MIME [headers.[](url)]([url]([url](
<img width="1246" alt="code commented" src="https://user-images.githubusercontent.com/4765792/213545881-78cbc81c-4c7e-496a-ab86-8ef040a43843.png">
<img width="1231" alt="stock 1 6" src="https://user-images.githubusercontent.com/4765792/213545850-25e1dffd-afc8-43f6-a812-645906dd0fae.png">)))

**Comment by alecpl** [comment]
Confirmed. It's also related to https://github.com/roundcube/roundcubemail/blob/25c2c991733decf535d9be4732c2dbe3162c14a8/program/lib/Roundcube/rcube_imap.php#L2232

**Comment by conathan** [comment]
I wanted to do a workaround for this to work for our client (#9147), and made a patch.  


Disclaimer: do not use.  There is a lot wrong with this approach (and wrong way to address the issue even)

If I understand the issue correctly, attachments that do not set Content-Disposition, are treated as inline images which do not appear in the list of downloadable attachments.  And in cases where not used by the html, also don't show up in the message body either.


I imagine a proper approach would be to check the message body to see if the image is actually used by the html code (unsure how to accomplish this at this time).

So instead,  patch checks if the return-path domain is vzwpix.com, (Testing this, works when message is direct, but not when viewing a .eml attachment from a forward message as.  This is due to the headers I am inspecting are from the main message, not the .eml message).  - Unsure how to get access to the .eml headers at this time.

[roundcubemail-verizon_fixattachments.patch.txt](https://github.com/roundcube/roundcubemail/files/12690899/roundcubemail-verizon_fixattachments.patch.txt)

**Comment by iredmail** [comment]
Dear @alecpl 

Any update?

**Comment by alecpl** [comment]
This is a more generic issue, that is not trivial to fix. But I made a fix for `application/smil` case described in here.
