### ISSUE TITLE
Issue with attachment_reminder with uploaded signature images

### ISSUE THREAD

**Issue by youradds** [roundcube/roundcubemail#8885]
Hi,

There seems to be a bug with the attachment_reminder plugin. It works fine when you have a normal <img href="http://xxxxx"> type format. But with the signatures, it offers the option to upload the signature - this is then base64 encoded (rather than a URL). I couldn't work out why the popup was coming up every time - and then after some trial and error I noticed it was the image in my signature.

Changing it to use a URL (rather than upload) has worked, but really it should take into account base64 stuff as well ;) I did have a look at the code to see if I could make an edit, but can't work out how it works :) (PHP isn't my strongpoint)

Cheers

Andy

**Comment by alecpl** [comment]
Confirmed. One of the strings we're looking for is "CV" which may occur in base64 data string. So, that's that, but the main reason for the issue is that we're searching in HTML content, instead of plain text representation. Also, we use very simple regexp which for searching words like "CV" is not that good idea.

**Comment by alecpl** [comment]
Still not perfect, but fixed.

**Comment by youradds** [comment]
Thanks for fixing so quickly :)
