### ISSUE TITLE
Recipient label text is partially unvisible in Finnish locale 

### ISSUE THREAD

**Issue by reflektoin** [roundcube/roundcubemail#8905]
Thank you for  developing this software!

Here's an image of the issue: 
The text left to the form field is partially blocked by the text field. The last letter is not completely visible.

![roundcube_recipient_edit_fi](https://user-images.githubusercontent.com/66482139/215860387-a7fa6f18-fa31-4762-8a3f-a1e1898bb622.png)

Steps to reproduce:
1. Change User interface language to Finnish.
2. Compose new message.
3. Add a recipient.
4. Double click the recipient.

Similar view as in the attached image should be now visible.

In English the "Vastaanottajan muokkaus" is "Recipient Edit".

**Comment by alecpl** [comment]
The css is the same for all single-input dialogs, e.g. Add Group. So, we need to fix it in a universal way.

I see three solutions:
1. Use `col-sm-3`/`col-sm-9` instead of `col-sm-2`/`col-sm-10`.
2. Use `text-truncate` class on the label.
3. Use `text-break` class on the label.

I'm not sure which I like the best.

https://github.com/roundcube/roundcubemail/blob/5d99ffb766bdb49efb2a8fe9d611f02d5776d0f2/skins/elastic/ui.js#L872-L874

**Comment by alecpl** [comment]
Fixed.
