### ISSUE TITLE
Empty charset cause not displaying

### ISSUE THREAD

**Issue by jackyzy823** [roundcube/roundcubemail#8919]
I have a weird mail which using empty ("") charset which cause roundcube can't display it.

```eml
Received: from somefrom.com (somefrom.com [123.123.123.123])
Message-Id: <random-1@random-string2>
Date: Sun, 12 Feb 2023 10:16:02 +0800 (CST)
MIME-Version: 1.0
Content-Type: Text/HTML;
  charset=""
From: some@somefrom.com
To: someto.com
Content-Transfer-Encoding: base64

xOO6ww==
```

After i add charset manually and import to roundcube it could display the content `你好`  correctly.
```eml
Received: from somefrom.com (somefrom.com [123.123.123.123])
Message-Id: <random-1@random-string2>
Date: Sun, 12 Feb 2023 10:16:02 +0800 (CST)
MIME-Version: 1.0
Content-Type: Text/HTML;
  charset="gb2312"
From: some@somefrom.com
To: someto.com
Content-Transfer-Encoding: base64

xOO6ww==
```

I don't know whether it is a bug. however i couldn't ask the sender to set charset correctly.

Besides  Thunderbird  will display text with wrong encoding  instead of displaying nothing.

**Comment by alecpl** [comment]
This depends on two things: 1) default charset in user preferences, 2) whether it is HTML or plain text message.

If your default charset is GB2312 the message will be displayed correctly. It's because we always do charset conversion to UTF-8. If your default charset is UTF-8 the conversion is omitted (the invalid characters pass through).

If your default charset is not GB2312 and the message is HTML all non-UTF-8 characters will get removed. We do this for our HTML sanitizer (in `rcmail_action_mail_index::wash_html()`). In plain text mode we do not remove invalid characters.

That being said, I'm not sure it's worth the effort to look for some other solutions. It's not an easy task and a rather rare case. If you often communicate in GB2312, set it as your default charset in Preferences > Displaying Messages > Advanced Options > Default character set.
