### ISSUE TITLE
Option to move emails to Trash when deleting folders

### ISSUE THREAD

**Issue by AuspeXeu** [roundcube/roundcubemail#9048]
It would be great if the user could choose to move the contents of a folder they delete to the trash instead of immediatelly deleting everything. Either via a separate button in the dialog like in the screenshot, or via an option in the settings.

![image](https://github.com/roundcube/roundcubemail/assets/2115696/4a26001a-cf72-4d30-b93e-b3055ed32e94)

**Comment by alecpl** [comment]
I suppose we could do it, but 
- does that mean move the folder to Trash or just the messages from it?
- having subfolders in Trash open other questions, e.g. should automatic Trash cleanup procedures delete such folders or not?
- last but not least, there are imap servers that do not allow both subfolders and messages in a folder.

Therefore we decided before that we'll not do this.

**Comment by AuspeXeu** [comment]
Maybe there could at least be a warning that the messages will be lost/delted and not in the Trash?

**Comment by AuspeXeu** [comment]
This is how outlook hands folder deletion, if you press **Yes**, the contents of the deleted folder get moved into deleted items.

![image](https://github.com/roundcube/roundcubemail/assets/2115696/0ccdc72c-5692-44d7-861a-06c05154ad44)

**Comment by medusared** [comment]
If it's not possible to create a subfolder of Trash due to some systems not supporting this, could just the emails from the deleted folder (and subfolders) be moved to the Trash folder instead? At least that way the emails would be recoverable, which in my opinion is much better than immediate deletion. It also wouldn't impact existing automatic Trash cleanup procedures, which could be kept the same, so seems like a good middle-ground solution.

And maybe have a setting in the config so admins can choose if this feature is on or off.
