### ISSUE TITLE
x-uuencode attachment in multipart/mixed message fails to decode

### ISSUE THREAD

**Issue by emtiu** [roundcube/roundcubemail#9096]
I regularly receive messages of `Content-Type: multipart/mixed` with an attached .pdf file that has the `Content-Transfer-Encoding: x-uuencode`.

Roundcube (currently on version 1.6.2) fails to decode these attachments: When trying to open or download the file, only a 2-byte-sized file is returned. No error message is logged.

However, if I take the source of this encoded attachment (from `begin 644 filename.pdf` to `end`) and pipe it through `uudecode` on the console, I obtain a correct, full-size valid .pdf file.

I have numerous example messages, but they all contain personal information, both in the e-mail body and the attachment. Luckily, I was able to craft a dummy message that triggers the bug: [test_message_uuencode_bug.txt](https://github.com/roundcube/roundcubemail/files/12312584/test_message_uuencode_bug.txt) (The attached PDF is a trivial sample document.)

**Comment by alecpl** [comment]
This is a regression introduced by 74b89fffde0a. We switched from parsing FETCH responses line by line to parsing in chunks, for performance reasons.

This issue is fixed by dfa18ab9d1e92.

I'm not closing this yet as we also need 
1. a workaround for Cyrus IMAP bug related to this. https://github.com/cyrusimap/cyrus-imapd/issues/4567
2. fix a regression in handling of quoted-printable and formatted text content.

**Comment by alecpl** [comment]
Decoding issues has been fixed. I opened a new ticket for the Cyrus issue.
