### ISSUE TITLE
SERVER ERROR! Error No. [600]

### ISSUE THREAD

**Issue by rcartists** [roundcube/roundcubemail#9101]

**Comment by alecpl** [comment]
It can be anything, e.g. misconfigured enigma plugin. Look into Roundcube error log for more context.

**Comment by francwalter** [comment]
Thank you for this hint! I had also this Error when opening identities:

![grafik](https://github.com/roundcube/roundcubemail/assets/927269/dd005853-446d-47d3-a49f-b9b2f727f1a4)

I disabled enigma in `$config['plugins']` in  `/var/www/roundcubemail/config/config.inc.php` and it worked. 
I just had installed v1.7.0 (dev, master from github) totally new, because my old roundcube had errors on upgrade, so I wanted to start new. 

In the error log `/var/log/roundcubemail/errors.log` first I found nothing about it. Later I noticed that the error.log is now in the Roundcube dir, in `/var/www/roundcubemail/logs/errors.log` and there the errors were :)

```
[23-Feb-2024 17:29:07 +0100]: <5am8s2pb> PHP Error: Enigma plugin: Option 'enigma_pgp_homedir' not specified in /var/www/roundcubemail/plugins/enigma/lib/enigma_engine.php on line 90 (GET /?
_task=settings&_action=edit-identity&_iid=1&_framed=1)
```
So I try to put my old config setting for log path in config again:
`$config['log_dir'] = '/var/log/roundcubemail/'`
but this gives an internal server error, not working.
So I wonder where I could find all working roundcube settings, because this log path setting I didnt find anywhere.
No way to set it up as in older rc versions?
