### ISSUE TITLE
Support for OpenID Connect Back-Channel Logout

### ISSUE THREAD

**Issue by azmeuk** [roundcube/roundcubemail#9110]
I suggest to implement helpers for [OIDC Back-Channel Logout](https://openid.net/specs/openid-connect-backchannel-1_0.html):

> This specification defines a logout mechanism that uses direct back-channel communication between the OP and RPs being logged out; this differs from front-channel logout mechanisms, which communicate logout requests from the OP to RPs via the User Agent.

This is the "mirror" spec of #9109. This would allow users to be disconnected from roundcube when they are disconnected from other services. This is very convenient for service providers offering several services (say nextcloud and roundcube for instance).

Technically that would consist in:
- providing a logout endpoint that the Identity Provider (IdP) will be able to reach
- decode and validate a JWT sent by the IdP at the logout endpoint
- logout the user

**Comment by EdouardVanbelle** [comment]
Hello I have started a POC where I can receive a backchannel logout request from the identity provider
I can found the ODIC sub and found the associated Roundcube's user 
(for that purpose I had to associate user to the OIDC sub)

The problem I have is that I cannot easily find all associated sessions for a given user. 
What I am thinking to do is something like: storing the logout event timestamp for a given sub. 
Then on any next refresh, if the associated user's token is older than the event I could raise a "session expired" without needing to query any server

Before going ahead it brings changes in database and I will appreciate feedbacks because I don't know the future evolution of Roundcube and I want to ensure a move forward aligned with the maintainers' vision

While waiting and seeing differently the problem: currently each time Roundcube does a refresh, it queries the IMAP server which may raise immediately a failure from the authentification request is OIDC session is burnt.

**Comment by EdouardVanbelle** [comment]
I have a simple solution:

each time we receive a back channel logout request I will store in cache the `sub` and the logout request `timestamp`
when a customer trigger a refresh I will check if the current oauth session for the same sub was generated before the logout request, if so I just have to kill_session 

Will test it later

Doing this no need to patch any database

**Comment by alecpl** [comment]
Implemented via #9217.
