### ISSUE TITLE
Windows 'mime.types' default path for XAMPP has a trailing dot

### ISSUE THREAD

**Issue by ner00** [roundcube/roundcubemail#9113]
This has worked fine for years, despite having an unnecessary extra char at the end of the path/filename, but it started giving me issue since migrating to a new version of XAMPP with PHP v8.2.4.
https://github.com/roundcube/roundcubemail/blob/a815867bca05c68dcec7fa836cc72c3816d7aaf6/program/lib/Roundcube/rcube_mime.php#L835

From now on I'll use `$config['mime_types'] = '/xampp/apache/conf/mime.types';` in `config.inc.php`, but would be nice if this was "fixed". 

On a side note, I'm curious about what changed in PHP which, after all these years, started determining that the trailing dot was out of place (this seems related: https://github.com/php/php-src/issues/9227).

**Comment by niklaskoskowski** [comment]
I think i have similar problems: 
I am using Roundcube on a Netcup Webhosting 8000 instance, recently wanted to update roundcube.

Since then, even if I try to reinstall the Backup, it stops at the mime.types config…

It shows not ok, even though I have mapped the correct path, where the file is located

**Comment by alecpl** [comment]
That file path was introduced in 02c9c931fe34c69. I do not recall from where I got this path, but the trailing dot is probably a typo.

**Comment by alecpl** [comment]
Fixed.
