### ISSUE TITLE
Preferences should not be highlighted upon arriving in settings

### ISSUE THREAD

**Issue by jidanni** [roundcube/roundcubemail#9454]
Here we have just arrived in settings. We see it assumes that we have apparently already pushed the preferences button, as it is colored in blue. However we don't see any choices below or anywhere. 
![Screenshot_20240518-133156.jpg](https://github.com/roundcube/roundcubemail/assets/1230959/46677e71-bac0-4ff3-a000-8505f3485496)

The bug, is clearly, that that blue should be white. Because we haven't actually pushed the preferences button yet. The same problem appears in the Larry skin too. 

This is a very simple bug to fix and very easy to understand. 

We have just landed in settings and each button should look exactly the same because we haven't touched any of them. 

It's simply incorrect for the first button to somehow indicate an already touched state. 

Sure, after we touch it then it can indicate that state but not before. Thank you.

**Comment by alecpl** [comment]
Looks like a custom skin. In Elastic on a phone the selected list item is not different that the rest. However, it indeed has a "selected" class assigned. I don't think we should or can easily remove the class on small screen only (the class is needed for bigger screen). I may re-consider if you provide a pull request. I think it should be fixed in the custom skin.

**Comment by jidanni** [comment]
Indeed checking again using a wide screen it all makes sense. Indeed if there was a reference skin included (#9453) then I could test all of these first before filing these bugs!
