### ISSUE TITLE
Install Requirements: unsafe-inline and unsafe-eval in script-src if CSP is in use

### ISSUE THREAD

**Issue by narcisgarcia** [roundcube/roundcubemail#9468]
Rouncube documentation in Github Wiki has a chapter dedicated to "Install Requirements".

An important information lacks to avoid many site administrators fail on deploying this software:
If **Content-Security-Policy** is in use at webserver, `script-src` parameter must include `'unsafe-inline' 'unsafe-eval'` so Rouncube works.
(as of version 1.6.5)

I hope in the future these specific configurations are not necessary so a Roundcube site can get a score of **A+** on web security observatories.

**Comment by pabzm** [comment]
You're right. Would you be interested to contribute that information and open a pull request for it?

There're some ideas on how to get closer to a stricter CSP, but that's still a lot of work, so it won't happen soon.

**Comment by narcisgarcia** [comment]
I can contribute if you link guide or indicate step-by-step how to pull request for it.

I've read all issues about Roundcube problems with a strict CSP-SOP, and is for current situation that I propose this mention in documentation.

**Comment by pabzm** [comment]
Please don't feel pressured If you don't feel comfortable with it! I just figured it would be the right thing to let you change the text since you're the one bringing it up.

If you're unsure how to do it, there's some documentation here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

But also feel free to ask :)

**Comment by pabzm** [comment]
@narcisgarcia Thanks again for suggesting this! 👍
