### ISSUE TITLE
Warning message from 1.6.6 to 1.6.7 upgrade

### ISSUE THREAD

**Issue by ozgurkazancci** [roundcube/roundcubemail#9469]
Hello.

Upgrading from 1.6.6 (complete) to 1.6.7 (complete), getting;

_WARNING: JavaScript dependencies update skipped. New jsdeps.json file not found._

during execution of installto.sh. What does the message really mean?

In my current 1.6.6. bin/ folder, I have: **install-jsdeps.sh** file.
But the new package from 1.6.7 does not have this file. Any idea on this, as well?

Regards.

**Comment by alecpl** [comment]
The "complete" packages do not include jsdeps.json file, because the dependencies are already included. On the other hand a "dependent" packages include jsdeps.json. You should not be mixing package types on update. Whenever such situation occurs we print a warning. It means that your jsdeps,json file is most likely outdated, but the dependencies should be up-to-date.

So, I suppose you can just delete that file and use complete packages.

I don't know, maybe in the future we'll just release one type of a package, there are some other reasons to do that.
