### ISSUE TITLE
Where is option to disable mail preview?

### ISSUE THREAD

**Issue by wqyutv** [roundcube/roundcubemail#9670]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I can recreate the issue with all plugins disabled

### Describe the issue

Where is option to disable mail preview? I do not want to open up emails from senders I do not know. 

### What version of Roundcube are you using?

1.6.8

**Comment by alecpl** [comment]
There's no such option. You can select mail with ctrl+click.

**Comment by KDCinfo** [comment]
My host just upgraded our Roundcube and ditched the Larry skin due to security issues. I spent the night installing Roundcube locally hoping a local install would allow me to disable the preview, but even adding `$config['layout'] = 'list';` to the config.inc.php didn't help (although the [defaults.inc.php](https://github.com/roundcube/roundcubemail/blob/master/config/defaults.inc.php#L1389) file said it would hide it). So it's seeming this is more of a Roundcube issue than a skin issue perhaps? 

In any case I really miss the list view, as I can barely see the subject lines enough to be able to visually identify spam. 😢 

I then saw a [plugin](https://github.com/johndoh/roundcube-elasticlayouts) was being offered, but that appears to have been archived. 

Picking through 100-200 emails is tedious with list view, and impossible without. Guess I'll take a look at Rainloop as suggested in the previously closed thread. 🤷‍♂ Other than the preview it's a nice app, so I'm glad it works for others. 👍
