### ISSUE TITLE
There should be a (no) SPAM icon

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [roundcube/roundcubemail#9723]
![Screenshot](https://github.com/user-attachments/assets/edf1741f-1f95-41a2-8250-8837e261951e)

![Screenshot](https://github.com/user-attachments/assets/aa990956-6f95-4940-b933-7a5f116dbc30)

It is also missing in the dark theme.

The font size does not look consistent either.

I use Roundcube under Firefox in the webmailer in version 1.5.9.

**Comment by johndoh** [comment]
This is a big guess based only on the fact in your image "kein Spam" has a lower case k. Is it possible you are still running the `markasjunk2` plugin which was discontinued with the release of Roundcube 1.4 rather than the `markasjunk` plugin that is distributed with Roundcube?

The basic issue appears to be which ever plugin you are using to add the Spam/Not Spam buttons into Roundcube does not support the Elastic skin - assuming that is the skin you are using but it looks like it.

- What skin are you using?
- What plugin are you using?

If I am right about you running the `markasjunk2` plugin then replace it with the `markasjunk` plugin distributed with Roundcube and the issue should disappear.

If you are already running the version of the `markasjunk` plugin distributed with 1.5.9 then more investigation will be needed to find the problem, if you look in the browser console are there any errors loading the CSS or anything like that?

If you are using some other 3<sup>rd</sup> party plugin then you need to contact the author of that plugin for support.

**Comment by 4jNsY6fCVqZv** [comment]
Thank you for your questions and support!

The hosting provider has now deactivated the `markasjunk2` plugin and the button has disappeared. Do they need to install the `markasjunk` plugin separately or is the functionality now included in Roundcube by default?

**Comment by johndoh** [comment]
If they want to enable similar functionality then the best way is to configure and activate the `markasjunk` plugin that is distributed with Roundcube.

As this is not a Roundcube issue please close this ticket.
